<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>CTilde</RootNamespace>
    <AssemblyName>CTilde.Compiler</AssemblyName>
    <PackageId>CTilde.Compiler</PackageId>
    <Version>0.15.0</Version>
    <AssemblyVersion>0.15.0.0</AssemblyVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Compiler/**/*.cs" />
    <EmbeddedResource Include="StandardLibrary/**/*.ct" LogicalName="CTilde.StandardLibrary.%(Filename)%(Extension)" />
    <EmbeddedResource Include="StandardLibrary/**/*.xml" LogicalName="CTilde.StandardLibrary.%(Filename)%(Extension)" />
    <EmbeddedResource Include="../third_party/ryu/4c0618b0/ryu/*" LogicalName="CTilde.Ryu.%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
