using CTilde;

namespace CTilde.Tests;

internal static partial class ConformanceTests
{
    public static void RegisterPart9(ConformanceSuite suite)
    {
        suite.Run("draft 0.12 vector standard library loading", () =>
        {
            const string noVectors = "public static class Program { [EntryPoint] public static void Main() { int value = 1 + 2; } }";
            var baseline = Emit(noVectors);
            Assert(baseline.StartsWith("/* Generated by C~ draft 0.23", StringComparison.Ordinal), "Generated C did not identify draft 0.23.");
            Assert(!baseline.Contains("Vec2", StringComparison.Ordinal) && !baseline.Contains("Vec3", StringComparison.Ordinal) && !baseline.Contains("Vec4", StringComparison.Ordinal), "Unused vector implementations were emitted.");
            using var headerWriter = new StringWriter();
            Assert(Compile(noVectors).EmitCHeader(headerWriter).Success, "Generated-header emission failed.");
            var header = headerWriter.ToString();
            Assert(header.Contains("#ifndef CTILDE_EXPORTS_", StringComparison.Ordinal), "The generated native header did not use a content-derived include guard.");
            Assert(header.Contains("#define CTILDE_RUNTIME_ABI_VERSION UINT32_C(16)", StringComparison.Ordinal), "The generated native header did not declare the draft 0.18 runtime ABI.");

            const string vec2Only = "public static class Program { [EntryPoint] public static void Main() { Vec2 value = Vec2.One; Console.WriteLine(value.X); } }";
            var generated = Emit(vec2Only);
            using var vectorMapWriter = new StringWriter();
            Assert(Compile(vec2Only).EmitSymbolMap(vectorMapWriter).Success, "Vector symbol-map emission failed.");
            var vectorMap = vectorMapWriter.ToString();
            Assert(vectorMap.Contains("Vec2", StringComparison.Ordinal), "A referenced Vec2 implementation was not emitted.");
            Assert(!vectorMap.Contains("Vec3", StringComparison.Ordinal) && !vectorMap.Contains("Vec4", StringComparison.Ordinal), "Unreferenced vector implementations were emitted with Vec2.");
            Assert(generated.Contains("ct_o_", StringComparison.Ordinal), "Vector operator implementations did not use operator mangling.");
            Assert(generated == Emit(vec2Only), "Vector emission was not deterministic.");

            foreach (var name in new[] { "Vec2", "Vec3", "Vec4" })
            {
                var source = $"public static class Program {{ [EntryPoint] public static void Main() {{ {name} value = {name}.Zero; Console.WriteLine(value.X); }} }}";
                var esp = Compile(source, new CompilationOptions(CompilationTarget.EspIdf));
                Assert(!esp.GetDiagnostics().Any(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error), $"{name} was unavailable for ESP-IDF: {string.Join(Environment.NewLine, esp.GetDiagnostics())}");
            }
        });

        suite.Run("draft 0.12 vector arithmetic and NoAlloc", () =>
        {
            const string source = """
                using System;
                public static class Program
                {
                    [NoAlloc]
                    private static Vec2 CheckVec2()
                    {
                        Vec2 value = new Vec2();
                        value.X = 2.0f;
                        value.Y = 4.0f;
                        value += Vec2.One;
                        value *= new Vec2(2.0f, 3.0f);
                        value /= new Vec2(2.0f, 5.0f);
                        value -= Vec2.UnitY;
                        value *= 2.0f;
                        value /= 2.0f;
                        return +(-(-value));
                    }

                    [NoAlloc]
                    private static Vec3 CheckVec3()
                    {
                        Vec3 value = new Vec3(1.0f, 2.0f, 3.0f) * new Vec3(2.0f, 4.0f, 6.0f);
                        value /= new Vec3(2.0f, 2.0f, 3.0f);
                        value = value * 2.0f;
                        value = 0.5f * value;
                        return value;
                    }

                    [NoAlloc]
                    private static Vec4 CheckVec4()
                    {
                        Vec4 value = new Vec4(2.0f);
                        value /= new Vec4(1.0f, 2.0f, 4.0f, 8.0f);
                        return value;
                    }

                    [EntryPoint]
                    public static void Main()
                    {
                        Vec2 two = CheckVec2();
                        Console.WriteLine((int)two.X);
                        Console.WriteLine((int)two.Y);
                        Console.WriteLine((int)new Vec2(3.0f, 4.0f).Length());
                        Vec2 normalized2 = new Vec2(3.0f, 4.0f).Normalize();
                        Console.WriteLine(normalized2.X > 0.59f && normalized2.X < 0.61f && normalized2.Y > 0.79f && normalized2.Y < 0.81f);

                        Vec3 three = CheckVec3();
                        Console.WriteLine((int)three.X);
                        Console.WriteLine((int)three.Y);
                        Console.WriteLine((int)three.Z);
                        Console.WriteLine((int)new Vec3(1.0f, 2.0f, 3.0f).Dot(new Vec3(4.0f, 5.0f, 6.0f)));
                        Console.WriteLine((int)new Vec3(1.0f, 2.0f, 3.0f).LengthSquared());
                        Vec3 cross = Vec3.UnitX.Cross(Vec3.UnitY);
                        Console.WriteLine(cross.X == 0.0f && cross.Y == 0.0f && cross.Z == 1.0f);

                        Vec4 four = CheckVec4();
                        Console.WriteLine(four.X == 2.0f && four.Y == 1.0f && four.Z == 0.5f && four.W == 0.25f);
                        Console.WriteLine((int)Vec4.One.Dot(Vec4.One));
                        Console.WriteLine(Vec4.UnitW.W == 1.0f);

                        Vec3 invalid = Vec3.Zero.Normalize();
                        Console.WriteLine(invalid.X != invalid.X && invalid.Y != invalid.Y && invalid.Z != invalid.Z);
                    }
                }
                """;
            var compilation = Compile(source);
            Assert(!compilation.GetDiagnostics().Any(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error), string.Join(Environment.NewLine, compilation.GetDiagnostics()));
            var result = CompileAndRun(source);
            Assert(result.ExitCode == 0, result.StandardError);
            Assert(Normalize(result.StandardOutput) == "3\n2\n5\nTrue\n1\n4\n6\n32\n14\nTrue\nTrue\n4\nTrue\nTrue\n", result.StandardOutput);
        });

        suite.Run("draft 0.12 vector language services and documentation", () =>
        {
            const string completionSource = "public static class P { public static void M() { Vec } }";
            const string path = "vector-completion.ct";
            var completionService = LanguageServiceSnapshot.Create([SyntaxTree.ParseText(completionSource, path)]);
            var completions = completionService.GetCompletions(path, completionSource.IndexOf("Vec }", StringComparison.Ordinal) + 3);
            Assert(new[] { "Vec2", "Vec3", "Vec4" }.All(name => completions.Any(completion => completion.Label == name)), "Editor completion did not preload every vector type.");

            const string source = "public static class P { [EntryPoint] public static void Main() { Vec3 left = Vec3.Zero; Vec3 right = Vec3.One; Vec3 result = left + right; } }";
            const string sourcePath = "vector-services.ct";
            var service = LanguageServiceSnapshot.Create([SyntaxTree.ParseText(source, sourcePath)]);
            Assert(!service.Diagnostics.Any(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error), string.Join(Environment.NewLine, service.Diagnostics));
            var typePosition = source.IndexOf("Vec3 left", StringComparison.Ordinal);
            var definition = service.GetDefinition(sourcePath, typePosition);
            Assert(definition?.FilePath == "stdlib/System/Vec3.ct", "Vec3 definition navigation did not target its embedded source.");

            var staticPosition = source.IndexOf("Vec3.Zero", StringComparison.Ordinal) + "Vec3.".Length;
            var zero = service.GetCompletions(sourcePath, staticPosition).Single(completion => completion.Label == "Zero");
            Assert(zero.DocumentationId is not null && service.GetDocumentation(zero.DocumentationId)?.Summary.Contains("zero vector", StringComparison.Ordinal) == true, "Vec3.Zero documentation was unavailable.");

            var plusPosition = source.LastIndexOf('+');
            var hover = service.GetHover(sourcePath, plusPosition);
            Assert(hover?.Sections.Any(section => section.Documentation?.Summary.Contains("Adds corresponding components", StringComparison.Ordinal) == true) == true, "Vector operator hover documentation was unavailable.");
        });
    }
}
