using System.Globalization;
using CTilde;

namespace CTilde.Tests;

internal static partial class ConformanceTests
{
    public static void RegisterPart22(ConformanceSuite suite)
    {
        var options = new CompilationOptions(CompilationTarget.Cosmopolitan, Architecture: CompilationArchitecture.X64);

        suite.Run("draft 0.24 Cosmopolitan profile and hosted runtime", () =>
        {
            const string source = """
                using System;
                using System.Runtime;

                public static class Program
                {
                    [EntryPoint]
                    public static void Main()
                    {
                        static if (Target.Profile == TargetProfile.Cosmopolitan)
                        {
                            Console.WriteLine("ape");
                            if (Target.PointerSize != 8) Console.WriteLine("bad pointer size");
                        }
                        else
                        {
                            Console.WriteLine("wrong profile");
                        }
                    }
                }
                """;
            var compilation = Compile(source, options);
            var diagnostics = compilation.GetDiagnostics();
            Assert(!diagnostics.Any(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error), string.Join(Environment.NewLine, diagnostics));
            var generated = Emit(source, options);
            Assert(generated.StartsWith($"/* Generated by C~ draft {CompilerContract.DraftVersion}", StringComparison.Ordinal), "Cosmopolitan output did not identify the current draft.");
            Assert(generated.Contains("int main(", StringComparison.Ordinal) && generated.Contains("ct_runtime_initialize", StringComparison.Ordinal),
                "Cosmopolitan output did not retain hosted startup and runtime lifecycle semantics.");
            Assert(generated.Contains("ct_write_string", StringComparison.Ordinal) && generated.Contains("fwrite", StringComparison.Ordinal),
                "Hosted I/O was not available to the Cosmopolitan profile.");
        });

        suite.Run("draft 0.24 Cosmopolitan architecture contract", () =>
        {
            const string source = "public static class Program { [EntryPoint] public static void Main() { } }";
            Assert(Compile(source, new CompilationOptions(CompilationTarget.Cosmopolitan)).GetDiagnostics()
                .Any(diagnostic => diagnostic.Code == "CT4118"), "Cosmopolitan architecture auto-detection was accepted.");
            Assert(Compile(source, new CompilationOptions(CompilationTarget.Cosmopolitan, Architecture: CompilationArchitecture.Arm64)).GetDiagnostics()
                .Any(diagnostic => diagnostic.Code == "CT4118"), "The deferred Arm64 Cosmopolitan target was accepted.");
        });

        suite.Run("draft 0.24 Cosmopolitan project and CLI", () =>
        {
            var directory = Path.Combine(Path.GetTempPath(), "ctilde-cosmopolitan-project-tests", Guid.NewGuid().ToString("N", CultureInfo.InvariantCulture));
            Directory.CreateDirectory(Path.Combine(directory, "src"));
            try
            {
                File.WriteAllText(Path.Combine(directory, "src", "Program.ct"),
                    "public static class Program { [EntryPoint] public static void Main() { } }");
                var manifestPath = Path.Combine(directory, "ctilde.json");
                File.WriteAllText(manifestPath, """
                    {
                      "target": "cosmopolitan",
                      "architecture": "x64",
                      "sources": ["src/**/*.ct"],
                      "build": { "configuration": "release", "compiler": "wsl:/opt/cosmocc/bin/x86_64-unknown-cosmo-cc", "executable": "build/program.com" },
                      "cosmopolitan": { "mode": "tiny" }
                    }
                    """);
                var project = CTildeProjectFile.Load(manifestPath);
                Assert(project.Configuration.Target == CompilationTarget.Cosmopolitan &&
                    project.Configuration.Architecture == CompilationArchitecture.X64 &&
                    project.Configuration.Cosmopolitan?.Mode == CosmopolitanRuntimeMode.Tiny,
                    "The Cosmopolitan project target, architecture, or runtime mode was not loaded.");
                Assert(project.Configuration.Build.Compiler == "wsl:/opt/cosmocc/bin/x86_64-unknown-cosmo-cc",
                    "A WSL Cosmopolitan wrapper path was incorrectly resolved as a project file.");
                Assert(project.Configuration.Build.ExecutablePath?.EndsWith("program.com", StringComparison.OrdinalIgnoreCase) == true,
                    "The Cosmopolitan APE output path was not resolved.");

                var configuration = new DirectoryInfo(AppContext.BaseDirectory).Parent?.Name ?? "Debug";
                var cliDll = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "CTilde.Cli", "bin", configuration, "net10.0", "ctilde.dll"));
                var check = RunProcess("dotnet", [cliDll, "--project", manifestPath, "--check"]);
                Assert(check.ExitCode == 0, $"Cosmopolitan project CLI check failed: {check.StandardOutput}{check.StandardError}");
                var invalid = RunProcess("dotnet", [cliDll, Path.Combine(directory, "src", "Program.ct"), "--target", "cosmopolitan", "--architecture", "arm64", "--check"]);
                Assert(invalid.ExitCode == 2 && invalid.StandardError.Contains("require --architecture x64", StringComparison.Ordinal),
                    "The CLI did not reject a deferred Cosmopolitan architecture.");
            }
            finally
            {
                Directory.Delete(directory, recursive: true);
            }
        });

        suite.Run("draft 0.24 Cosmopolitan language services", () =>
        {
            const string path = "cosmopolitan.ct";
            const string source = "using System; public static class Program { [EntryPoint] public static void Main() { Cons } }";
            var service = LanguageServiceSnapshot.Create([SyntaxTree.ParseText(source, path)], options);
            var position = source.IndexOf("Cons", StringComparison.Ordinal) + 4;
            Assert(service.GetCompletions(path, position).Any(item => item.Label == "Console"),
                "Cosmopolitan language services did not expose the hosted standard library.");
        });
    }
}
