namespace CTilde.Tests;

internal static class ConformanceTestCatalog
{
    public static readonly IReadOnlySet<string> CrossToolchain = new HashSet<string>(StringComparer.Ordinal)
    {
        "64-bit integers",
        "ARC cycle limitation",
        "ARC deterministic lifetime",
        "ARC native ownership and unsafe manual counts",
        "ARC properties arrays virtual calls and defer captures",
        "ARC returns exceptions and iterative destruction",
        "bounds failure",
        "by-reference callable ABI",
        "C float literal formatting",
        "CLI preserves unchanged generated timestamps",
        "complete feature example",
        "constant folding in switch",
        "constructor order and virtual dispatch",
        "defer capture order and transfers",
        "defer syntax diagnostics and cleanup exceptions",
        "draft 0.10 attached native threads",
        "draft 0.10 invalid attachment lifecycle",
        "draft 0.10 unattached native entry",
        "draft 0.11 operator evaluation and ARC",
        "draft 0.11 operator lowering and mangling",
        "draft 0.12 cleanup and reachability emission",
        "draft 0.12 fused strings and terminated native paths",
        "draft 0.12 vector arithmetic and NoAlloc",
        "draft 0.13 inline assembly GNU runtime",
        "draft 0.14 catchable runtime faults and allocation-free OOM",
        "draft 0.14 native lifecycle finalization and panic callback",
        "draft 0.14 native managed layout probe",
        "draft 0.15 abstract interface dispatch and generic constraints",
        "draft 0.15 atomic ordering and thread lifecycle failures",
        "draft 0.15 cleanup liveness and owned moves",
        "draft 0.15 interfaces generics atomics threads and locks runtime",
        "draft 0.16 aggregate layouts and operators runtime",
        "draft 0.17 section native object placement",
        "draft 0.17 section runtime behavior",
        "draft 0.18 target queries static if and assertions",
        "draft 0.19 alignment newtypes and CPU intrinsics",
        "draft 0.19 constant generics and inline arrays",
        "draft 0.20 bitfields and registers",
        "draft 0.20 endian values",
        "draft 0.25 assembly function GNU runtime",
        "draft 0.27 binary64 syntax semantics and runtime",
        "draft 0.28 fixed-width SIMD scalar semantics",
        "draft 0.29 Unicode rune literals and UTF-8 runtime",
        "draft 0.30 immutable owner-relative embedded resources",
        "draft 0.31 captureless lambdas",
        "draft 0.32 explicit value captures and ARC closures",
        "draft 0.35 array edge cases captures and exceptional cleanup",
        "draft 0.35 generic containers and array algorithms runtime",
        "draft 0.35 UTF-8 helpers validate and preserve failure outputs",
        "draft 0.36 defaults collections enumeration and iterators",
        "draft 0.37 scalar SIMD matrices and quaternions",
        "draft 0.38 hosted x64 packet SIMD operations",
        "draft 0.38 hosted x64 scalar geometry lowering",
        "draft 0.38 HostedIo packet golden and traversal fixtures",
        "draft 0.38 Vec3x4 layout semantics and ABI",
        "draft 0.39 native-import fixture ABI and startup",
        "draft 0.39 native-import startup failure",
        "draft 0.40 comparison operators and TimeSpan",
        "draft 0.40 deterministic Random",
        "draft 0.40 monotonic Stopwatch",
        "draft 0.40 spin primitives",
        "draft 0.40 scalar Math expansion",
        "draft 0.41 ordinal string operations and split segments",
        "draft 0.41 invariant formatting and StringBuilder",
        "draft 0.41 inline runtime hot paths",
        "draft 0.41 ARC fast paths and lazy identity hash",
        "draft 0.41 public ARC attachment contract",
        "draft 0.41 sealed receiver devirtualization",
        "draft 0.41 checked native UTF-8 conversion",
        "draft 0.41 native UTF-8 fixture ownership",
        "draft 0.42 invariant scalar and enum parsing",
        "draft 0.42 hosted streams UTF-8 and filesystem",
        "draft 0.43 freestanding standard-library runtime services",
        "draft 0.44 stack usage contracts and metadata",
        "draft 0.44 GCC stack report analysis",
        "draft 0.44 flattened SAH BVH construction and equivalence",
        "draft 0.8 native ABI foundations",
        "enum and struct object behavior",
        "Environment Exit",
        "exception C lowering snapshot",
        "exception catches rethrow and finally",
        "exception cleanup transfers and stack state",
        "exception finally diagnostics and replacement",
        "exception unhandled and null failures",
        "exceptions across constructors virtual calls and catches",
        "hosted console EOF and I/O exceptions",
        "hosted console line edge cases",
        "hosted file mode and buffer writes",
        "hosted path tracer deterministic native render",
        "hosted path tracer model and deterministic sampling",
        "hosted runtime files stage atomically and clean by receipt",
        "HostedIo Raylib ABI, dirty uploads, cadence, and lifecycle",
        "integer division failure",
        "left-to-right native execution",
        "lexical forms and standard library overloads",
        "named delegates and ARC",
        "native-sized integer rules",
        "negative array length failure",
        "null failure",
        "null string ToString failure",
        "numeric promotion and compound assignment",
        "object cast runtime failures",
        "object model example",
        "objects arrays strings and control flow",
        "project manifest and CLI",
        "scalar ToString",
        "short circuit and string equality",
        "System.Math emission and native behavior",
        "System.Object inheritance dispatch and boxing",
        "unmanaged function pointers",
        "unsafe pointer object boxing",
        "while do break and continue",
    };
}
