using CTilde.Expr;
using CTilde.FishAsm;
using System;
using System.CodeDom;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.ComTypes;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace CTilde.Langs
{
	public class FishAsmProvider : LangProvider
	{
		//bool OmmitSemicolon = false;
		FishCompileState State;

		public FishAsmProvider(FishCompileState State)
		{
			this.State = State;

			EmitRaw("# Generated by C~");
			EmitRaw("# Labels generate in the bytecode bin as the show up in the code, adjecent labels share address by design");
			EmitRaw("# int_table address is set by the VM when the program runs");
		}

		string FormatArgs(object[] args)
		{
			string[] argsStr = new string[args.Length];

			for (int i = 0; i < args.Length; i++)
			{
				if (args[i] is Reg R)
				{
					argsStr[i] = FishUtils.RegToString(R);
				}
				else if (args[i] is uint UI)
				{
					argsStr[i] = string.Format("${0}", UI);
				}
				else
				{
					argsStr[i] = args[i].ToString();
				}
			}

			return string.Join(", ", argsStr);
		}

		const bool SkipDuplicates = true;
		FishInst LastInst;
		object[] LastArgs;
		FishInst[] AllowSkip = new FishInst[] { FishInst.MOVE_REG_OFFSET_REG };

		void EmitInstruction(FishInst inst, params object[] args)
		{
			if (SkipDuplicates)
			{
				if (inst == LastInst && args.Length == LastArgs.Length && args.SequenceEqual(LastArgs) && AllowSkip.Contains(inst))
				{
					//EmitRawUnindented("# Skipping duplicate instruction {0} {1}", inst, FormatArgs(args));
					return;
				}

				LastInst = inst;
				LastArgs = args;
			}

			//Indent();
			AppendLine("{0} {1}", inst, FormatArgs(args));
			//Unindent();
		}

		void EmitRaw(string raw)
		{
			AppendLine(raw);
		}

		void EmitRaw(string fmt, params object[] args)
		{
			EmitRaw(string.Format(fmt, args));
		}

		void EmitRawUnindented(string fmt, params object[] args)
		{
			bool Unindented = false;
			if (Unindent())
				Unindented = true;

			EmitRaw(string.Format(fmt, args));

			if (Unindented)
				Indent();
		}

		void EmitLabels()
		{
			FishLabel[] Lbls = State.GetNewLabels();

			foreach (FishLabel L in Lbls)
			{
				EmitRaw(L.Name + ":");
				Indent();

				if (L.Value.StartsWith("\"") && L.Value.EndsWith("\""))
				{
					EmitRaw(".String {0}", L.Value);
				}
				else
				{
					EmitRaw(".long {0}", L.Value);
				}

				Unindent();
			}
		}

		void EmitReturn()
		{
			EmitInstruction(FishInst.LEAVE);
			EmitInstruction(FishInst.RET);
		}

		public override void Compile(Expression Ex)
		{
			if (Ex == null)
				throw new ArgumentNullException(nameof(Ex));

			switch (Ex)
			{
				case Expr_Block Block:
					{
						//AppendLine("{");

						foreach (var E in Block.Expressions)
						{
							Compile(E);
						}

						//AppendLine("}");
						break;
					}

				case Expr_ClassDef ClassDef:
					{
						AppendLine("typedef struct {");

						foreach (var E in ClassDef.Variables)
						{
							Compile(E);
						}

						AppendLine("}} {0};", ClassDef.Name);

						foreach (var F in ClassDef.Functions)
						{
							Compile(F);
						}
						break;
					}

				case Expr_FuncDef FuncDef:
					{
						EmitRaw(".globl {0}", FuncDef.FuncName);
						State.DefineLabel(FuncDef.FuncName, true);

						if (FuncDef.FuncBody != null)
						{
							State.ClearVarOffsets();
							State.ClearArgOffset();

							EmitRaw("{0}:", FuncDef.FuncName);
							Indent();
							State.IsInsideFunctionDef = true;

							if (!FuncDef.Naked)
							{
								EmitInstruction(FishInst.PUSH_REG, Reg.EBP);
								EmitInstruction(FishInst.MOVE_REG_REG, Reg.ESP, Reg.EBP);
							}

							//OmmitSemicolon = true;
							//Compile(FuncDef.FuncReturnTypeDef);
							//Append(" {0}(", FuncDef.FuncName);

							Compile(FuncDef.FuncParams);

							//Append(")");
							//OmmitSemicolon = false;

							State.IsInsideFunctionDef = false;
							State.IsInsideFunctionBody = true;

							Compile(FuncDef.FuncBody);

							if (!FuncDef.Naked)
							{
								EmitReturn();
							}
							State.IsInsideFunctionBody = false;
							Unindent();

							//EmitLabels();

						}
						break;
					}

				case Expr_Module Module:
					{
						foreach (var E in Module.Expressions)
							Compile(E);

						EmitLabels();
						break;
					}

				case Expr_ParamsDef ParamsDef:
					{
						for (int i = 0; i < ParamsDef.Definitions.Count; i++)
						{
							ParamDefData ParamDef = ParamsDef.Definitions[i];
							//Compile(ParamDef);

							/*Compile(ParamDef.ParamType);
							Append(" {0}", ParamDef.Name);

							if (i + 1 < ParamsDef.Definitions.Count)
								Append(", ");*/

							int Size = State.GetTypeSize(ParamDef.ParamType);
							State.DefineVar(ParamDef.Name, Size, true, ParamDef.ParamType, false, true);
						}

						break;
					}

				case Expr_TypeDef TypeDef:
					{
						string T = TypeDef.Type;

						if (TypeDef.IsPointer)
							T += "*";
						else if (TypeDef.IsArray)
							T += "[]";

						Append(T);
						break;
					}

				case Expr_StaticValue StaticValueExpr:
					{
						string StatVar = State.DefineFreeLabel("STATVAR", false);
						EmitRaw("{0}:", StatVar);

						if (StaticValueExpr.TypeDefExpr.Type == "string" && StaticValueExpr.TypeDefExpr.IsArray)
						{
							EmitRaw(".Raw {0}, {1}", StaticValueExpr.TypeDefExpr.ArraySize, 0);
						}

						break;
					}

				case Expr_VariableDef VariableDef:
					{
						/*Compile(VariableDef.Type);
						Append(" ");
						Compile(VariableDef.Ident);
						AppendLine(";");*/

						EmitRaw("# VariableDef BEGIN - {0}", VariableDef.Ident.Identifier);
						Indent();

						if (!State.IsInsideFunctionBody)
						{
							State.DefineLabel(VariableDef.Ident.Identifier, true);
							EmitRaw(".globl {0}", VariableDef.Ident.Identifier);

							int Size = State.GetTypeSize(VariableDef.Type);
							State.DefineVar(VariableDef.Ident.Identifier, Size, false, VariableDef.Type, true, false);
						}
						else
						{
							int Size = State.GetTypeSize(VariableDef.Type);
							State.DefineVar(VariableDef.Ident.Identifier, Size, false, VariableDef.Type, false, false);

							EmitInstruction(FishInst.SUB_LONG_REG, (uint)Size, Reg.ESP);
						}

						Unindent();
						EmitRaw("# VariableDef END - {0}", VariableDef.Ident.Identifier);
						/*if (!OmmitSemicolon)
							AppendLine(";");*/

						break;
					}

				case Expr_AssignedVariableDef AssVariableDef:
					{
						EmitRaw("# VariableDef BEGIN - {0}", AssVariableDef.VariableDef.Ident.Identifier);
						Indent();

						int Size = State.GetTypeSize(AssVariableDef.VariableDef.Type);
						bool Global = State.IsInsideFunctionBody ? false : true;

						State.DefineVar(AssVariableDef.VariableDef.Ident.Identifier, Size, false, AssVariableDef.VariableDef.Type, Global, false);

						if (State.IsInsideFunctionBody)
						{
							EmitInstruction(FishInst.SUB_LONG_REG, (uint)Size, Reg.ESP);
						}
						else
						{
							State.DefineLabel(AssVariableDef.VariableDef.Ident.Identifier, true);
							EmitRaw(".globl {0}", AssVariableDef.VariableDef.Ident.Identifier);
							EmitRaw("{0}:", AssVariableDef.VariableDef.Ident.Identifier);
						}

						Unindent();
						EmitRaw("# VariableDef END - {0}", AssVariableDef.VariableDef.Ident.Identifier);

						EmitRaw("# VariableAssign BEGIN");
						Indent();

						Compile(AssVariableDef.AssignmentValue);

						if (State.IsInsideFunctionBody)
						{
							int VarID = State.GetVarOffset(AssVariableDef.VariableDef.Ident.Identifier);
							EmitInstruction(FishInst.MOVE_REG_OFFSET_REG, Reg.EAX, VarID, Reg.EBP);
						}

						Unindent();
						EmitRaw("# VariableAssign END");
						break;
					}

				case Expr_AssignValue AssValue:
					{
						if (AssValue.LExpr is Expr_IndexOp IndexOp)
						{
							EmitRaw("# Expr_AssignValue BEGIN");
							Indent();

							State.IndexEmitOnlyAddress = true;
							Compile(AssValue.LExpr);
							State.IndexEmitOnlyAddress = true;

							EmitInstruction(FishInst.MOVE_REG_REG, Reg.EAX, Reg.EBX);

							Compile(AssValue.ValueExpr);
							int CopyBytes = 0;

							if (IndexOp.LExpr is Expr_Identifier Id)
							{
								Expr_TypeDef VarType = State.GetVarType(Id.Identifier);
								CopyBytes = State.GetPointerTypeSize(VarType);

								if (CopyBytes == 1)
									EmitInstruction(FishInst.MOVEBYTE_REG_OFFSET_REG, Reg.EAX, 0, Reg.EBX);
								else if (CopyBytes == 2)
								{
									EmitInstruction(FishInst.MOVEBYTE_REG_OFFSET_REG, Reg.AL, 0, Reg.EBX);
									EmitInstruction(FishInst.MOVEBYTE_REG_OFFSET_REG, Reg.AH, 1, Reg.EBX);
								}
								else if (CopyBytes == 4)
									EmitInstruction(FishInst.MOVE_REG_OFFSET_REG, Reg.EAX, 0, Reg.EBX);
								else
									throw new NotImplementedException();
							}
							else
								throw new NotImplementedException();

							if (CopyBytes == 4)
								EmitInstruction(FishInst.MOVE_REG_OFFSET_REG, Reg.EAX, 0, Reg.EBX);
							//EmitRaw("# REST OF ASSVALUE HERE");

							Unindent();
							EmitRaw("# Expr_AssignValue END");
						}
						else
							throw new NotImplementedException();

						break;
					}

				case Expr_AssignVariable AssVariable:
					{
						Compile(AssVariable.AssignmentValue);

						int VarID = State.GetVarOffset(AssVariable.Variable.Identifier);
						EmitInstruction(FishInst.MOVE_REG_OFFSET_REG, Reg.EAX, VarID, Reg.EBP);

						break;
					}

				case Expr_Identifier IdentifierEx:
					{
						//Expr_TypeDef TypeDef = State.GetVarType(IdentifierEx.Identifier);

						if (State.IsVarGlobal(IdentifierEx.Identifier))
						{
							EmitInstruction(FishInst.MOVE_LONG_REG, IdentifierEx.Identifier, Reg.EAX);
						}
						else
						{
							int VarOffset = State.GetVarOffset(IdentifierEx.Identifier);
							EmitInstruction(FishInst.MOVE_OFFSET_REG_REG, VarOffset, Reg.EBP, Reg.EAX);
						}
						//Append(IdentifierEx.Identifier);
						break;
					}

				case Expr_ConstNumber NumberEx:
					{
						//Append(NumberEx.NumberLiteral);
						uint Num = uint.Parse(NumberEx.NumberLiteral);

						if (State.IsInsideFunctionBody)
						{
							EmitInstruction(FishInst.MOVE_LONG_REG, Num, Reg.EAX);
						}
						else
							EmitRaw(".long {0}", Num);

						break;
					}

				case Expr_ConstString StringEx:
					{
						//EmitRaw(".globl {0}", StringEx.StringLiteral);
						string LblName = State.DefineLabel(null, StringEx.StringLiteral);

						EmitInstruction(FishInst.MOVE_LONG_REG, LblName, Reg.EAX);
						//Append(StringEx.StringLiteral);
						break;
					}

				case Expr_ConstChar CharEx:
					{
						EmitInstruction(FishInst.MOVES_LONG_REG, (uint)CharEx.CharLiteral, Reg.EAX);
						break;
					}

				case Expr_MathOp MathExp:
					{
						EmitRaw("# MathOp BEGIN ({0})", MathExp.OpString);
						Indent();
						EmitInstruction(FishInst.PUSH_REG, Reg.EBX);

						Compile(MathExp.LExpr);

						EmitInstruction(FishInst.MOVE_REG_REG, Reg.EAX, Reg.EBX);

						//Append(" {0} ", MathExp.OpString);
						Compile(MathExp.RExpr);

						switch (MathExp.Op)
						{
							case MathOperation.Add:
								EmitInstruction(FishInst.ADD_REG_REG, Reg.EBX, Reg.EAX);
								break;

							case MathOperation.Sub:
								EmitInstruction(FishInst.SUB_REG_REG, Reg.EBX, Reg.EAX);
								break;

							default:
								throw new NotImplementedException();
						}

						EmitInstruction(FishInst.POP_REG, Reg.EBX);
						Unindent();
						EmitRaw("# MathOp END ({0})", MathExp.OpString);

						break;
					}

				case Expr_ComparisonOp CompExpr:
					{
						Compile(CompExpr.LExpr);
						EmitInstruction(FishInst.MOVE_REG_REG, Reg.EAX, Reg.EBX);
						Compile(CompExpr.RExpr);

						EmitInstruction(FishInst.CMP_REG_REG, Reg.EAX, Reg.EBX);

						/*switch (CompExpr.Op)
						{
							case ComparisonOp.Equals:
								throw new NotImplementedException();
								break;

							case ComparisonOp.NotEquals:
								EmitRaw("# NOTEQUALS"); 
								throw new NotImplementedException();
								break;

							default:
								throw new NotImplementedException();
						}*/

						break;
					}

				case Expr_IfElseStatement IfExpr:
					{
						EmitRaw("# If BEGIN");
						Indent();

						string EndLblName = State.DefineFreeLabel("ENDIF", false);
						string ElseLblName = EndLblName;

						if (IfExpr.ElseBody != null)
							ElseLblName = State.DefineFreeLabel("ELSE", false);

						Compile(IfExpr.ConditionValue);

						if (IfExpr.ConditionValue is Expr_ComparisonOp Cmp)
						{
							if (Cmp.Op == ComparisonOp.Equals)
							{
								EmitInstruction(FishInst.JUMP_IF_NOT_ZERO_LONG, ElseLblName);
							}
							else if (Cmp.Op == ComparisonOp.NotEquals)
							{
								EmitInstruction(FishInst.JUMP_IF_ZERO_LONG, ElseLblName);
							}
							else if (Cmp.Op == ComparisonOp.GreaterThan)
							{
								EmitInstruction(FishInst.JUMP_IF_GREAT_LONG, ElseLblName);
							}
							else if (Cmp.Op == ComparisonOp.LessThan)
							{
								EmitInstruction(FishInst.JUMP_IF_LESS_LONG, ElseLblName);
							}
							else if (Cmp.Op == ComparisonOp.GreaterThanOrEqual)
							{
								EmitInstruction(FishInst.JUMP_IF_GREATEQ_LONG, ElseLblName);
							}
							else if (Cmp.Op == ComparisonOp.LessThanOrEqual)
							{
								EmitInstruction(FishInst.JUMP_IF_LESSEQ_LONG, ElseLblName);
							}
							else
								throw new NotImplementedException();

						}
						else
							throw new NotImplementedException();

						State.PushBreakLabel(EndLblName);
						Compile(IfExpr.Body);
						State.PopBreakLabel();

						if (IfExpr.ElseBody != null)
						{
							EmitInstruction(FishInst.JUMP_LONG, EndLblName);
							Unindent();
							EmitRaw("# Else BEGIN");
							Indent();
							EmitRaw("{0}:", ElseLblName);

							State.PushBreakLabel(EndLblName);
							Compile(IfExpr.ElseBody);
							State.PopBreakLabel();

							Unindent();
							EmitRaw("# Else END");
							Indent();
						}

						EmitRaw("{0}:", EndLblName);

						Unindent();
						EmitRaw("# If END");
						break;
					}

				case Expr_WhileStatement WhileExpr:
					{
						EmitRaw("# While BEGIN");
						Indent();

						string LblName = State.DefineFreeLabel("WHILE", false);
						string EndLblName = State.DefineFreeLabel("ENDWHILE", false);
						EmitRaw("{0}:", LblName);

						if (WhileExpr.ConditionValue is Expr_ComparisonOp Cmp)
						{
							if (Cmp.Op == ComparisonOp.Equals)
							{
								Compile(WhileExpr.ConditionValue);
								EmitInstruction(FishInst.JUMP_IF_NOT_ZERO_LONG, EndLblName);
							}
							else if (Cmp.Op == ComparisonOp.NotEquals)
							{
								Compile(WhileExpr.ConditionValue);
								EmitInstruction(FishInst.JUMP_IF_ZERO_LONG, EndLblName);
							}
							else
								throw new NotImplementedException();

						}
						else if (WhileExpr.ConditionValue is Expr_ConstNumber CNum)
						{
							if (CNum.NumberLiteral == "1")
							{
								EmitInstruction(FishInst.NOP);
							}
							else
								throw new NotImplementedException();
						}
						else
							throw new NotImplementedException();

						State.PushBreakLabel(EndLblName);

						if (WhileExpr.Body.Expressions.Count > 0)
						{
							//EmitRaw("# Body goes here");
							EmitInstruction(FishInst.PUSH_REG, Reg.EBX);
							EmitInstruction(FishInst.PUSH_REG, Reg.EAX);
							Compile(WhileExpr.Body);
							EmitInstruction(FishInst.POP_REG, Reg.EAX);
							EmitInstruction(FishInst.POP_REG, Reg.EBX);
						}

						State.PopBreakLabel();

						EmitInstruction(FishInst.JUMP_LONG, LblName);
						EmitRaw("{0}:", EndLblName);
						//throw new NotImplementedException();

						Unindent();
						EmitRaw("# While END");
						break;
					}

				case Expr_BreakExpr BreakExpr:
					{
						string BreakLbl = State.PeekBreakLabel();
						EmitInstruction(FishInst.JUMP_LONG, BreakLbl);

						break;
					}

				case Expr_AddressOfOp AddrOfExpr:
					{
						EmitRaw("# Expr_AddressOfOp BEGIN");
						Indent();

						if (AddrOfExpr.ValExpr is Expr_Identifier Ident)
						{
							EmitInstruction(FishInst.MOVE_LONG_REG, Ident.Identifier, Reg.EAX);
						}
						else
							throw new NotImplementedException();

						Unindent();
						EmitRaw("# Expr_AddressOfOp END");
						break;
					}

				case Expr_IndexOp IndexExpr:
					{
						EmitRaw("# IndexOp BEGIN");
						Indent();

						// Compute index first => EAX = index
						Compile(IndexExpr.IndexValExpr); // index in EAX

						if (IndexExpr.LExpr is Expr_Identifier id)
						{
							Expr_TypeDef idType = State.GetVarType(id.Identifier);
							int elemSize = State.GetPointerTypeSize(idType);

							// Preserve (and scale) index in EBX
							EmitInstruction(FishInst.MOVE_REG_REG, Reg.EAX, Reg.EBX); // EBX = index

							if (elemSize > 1)
							{
								// scale index: EAX = elemSize, MUL EBX => EAX = elemSize * index
								EmitInstruction(FishInst.MOVE_LONG_REG, "$" + elemSize, Reg.EAX);
								EmitInstruction(FishInst.MUL_REG, Reg.EBX);
								EmitInstruction(FishInst.MOVE_REG_REG, Reg.EAX, Reg.EBX); // EBX = scaled index
							}

							// Load base pointer into EAX (Compile of identifier gives the pointer value)
							Compile(IndexExpr.LExpr); // EAX = base pointer

							// Effective address: base + scaled_index
							EmitInstruction(FishInst.ADD_REG_REG, Reg.EBX, Reg.EAX);

							// Load or leave address
							int copyBytes = State.GetPointerTypeSize(idType);
							bool isUnsigned = CTType.IsUnsigned(idType.Type);

							if (!State.IndexEmitOnlyAddress)
							{
								if (copyBytes == 1)
								{
									if (isUnsigned)
										EmitInstruction(FishInst.MOVEBYTE_OFFSET_REG_REG, 0, Reg.EAX, Reg.EAX);
									else
										EmitInstruction(FishInst.MOVES_OFFSET_REG_REG, 0, Reg.EAX, Reg.EAX);
								}
								else if (copyBytes == 2)
									EmitInstruction(FishInst.MOVEZ_OFFSET_REG_REG, 0, Reg.EAX, Reg.EAX);
								else if (copyBytes == 4)
									EmitInstruction(FishInst.MOVE_OFFSET_REG_REG, 0, Reg.EAX, Reg.EAX);
								else
									throw new NotImplementedException();
							}
						}
						else
						{
							// Existing non-identifier path kept (already does index first then base)
							EmitInstruction(FishInst.MOVE_REG_REG, Reg.EAX, Reg.EBX);
							Compile(IndexExpr.LExpr);
							EmitInstruction(FishInst.ADD_REG_REG, Reg.EBX, Reg.EAX);

							// (You may need to replicate the load logic here similar to above if required)
						}

						Unindent();
						EmitRaw("# IndexOp END");
						break;
					}

				case Expr_IncDecOp IncDecExp:
					{
						EmitRaw("# Expr_IncDecOp BEGIN");
						Indent();

						if (IncDecExp.LExpr is Expr_Identifier Id)
						{
							int VarOffset = State.GetVarOffset(Id.Identifier);
							Compile(IncDecExp.LExpr);

							if (IncDecExp.Inc)
								EmitInstruction(FishInst.ADD_LONG_REG, "$" + 1, Reg.EAX);
							else
								EmitInstruction(FishInst.SUB_LONG_REG, "$" + 1, Reg.EAX);

							EmitInstruction(FishInst.MOVE_REG_OFFSET_REG, Reg.EAX, VarOffset, Reg.EBP);
						}
						else
							throw new NotImplementedException();

						Unindent();
						EmitRaw("# Expr_IncDecOp END");
						break;
					}

				case Expr_ReturnStatement ReturnExp:
					{
						EmitRaw("# Expr_ReturnStatement BEGIN");
						Indent();

						if (ReturnExp.RetValExpr != null)
						{
							Compile(ReturnExp.RetValExpr);
						}

						EmitReturn();


						Unindent();
						EmitRaw("# Expr_ReturnStatement END");
						break;
					}

				case Expr_FuncCall FuncCallExp:
					{
						if (FuncCallExp.Function.Identifier == "__asm")
						{
							foreach (var Arg in FuncCallExp.Arguments)
							{
								if (Arg is Expr_ConstString S)
								{
									EmitRaw(S.RawString);
								}
								else
								{
									throw new NotImplementedException("Only string literals are supported in __asm");
								}
							}
						}
						else if (FuncCallExp.Function.Identifier == "syscall_2")
						{
							EmitRaw("# syscall_2 BEGIN");
							Indent();

							if (FuncCallExp.Arguments.Count != 2)
								throw new Exception("syscall_2 requires exactly 2 arguments");

							Expr_ConstNumber NumExp = FuncCallExp.Arguments[0] as Expr_ConstNumber;
							Expression A0 = FuncCallExp.Arguments[1];

							Compile(A0);
							EmitInstruction(FishInst.PUSH_REG, Reg.EAX);
							EmitInstruction(FishInst.MOVE_LONG_REG, "$" + NumExp.NumberLiteral, Reg.EAX);
							EmitInstruction(FishInst.PUSH_REG, Reg.EAX);

							EmitInstruction(FishInst.SYSCALL_2);

							/*foreach (var Arg in FuncCallExp.Arguments)
							{
								if (Arg is Expr_ConstString S)
								{
									EmitRaw(S.RawString);
								}
								else
								{
									throw new NotImplementedException("Only string literals are supported in __asm");
								}
							}*/

							Unindent();
							EmitRaw("# syscall_2 END");
						}
						else
						{
							EmitRaw("# FuncCall BEGIN - {0}", FuncCallExp.Function.Identifier);
							Indent();

							for (int i = 0; i < FuncCallExp.Arguments.Count; i++)
							{
								Compile(FuncCallExp.Arguments[i]);
								EmitInstruction(FishInst.PUSH_REG, Reg.EAX);
							}

							EmitInstruction(FishInst.MOVE_LONG_REG, FuncCallExp.Function.Identifier, Reg.EAX);
							EmitInstruction(FishInst.CALL_REG, Reg.EAX);

							EmitInstruction(FishInst.ADD_LONG_REG, (uint)(FuncCallExp.Arguments.Count * 4), Reg.ESP);

							/*throw new NotImplementedException();

							Compile(FuncCallExp.Function);

							Append("(");


							for (int i = 0; i < FuncCallExp.Arguments.Count; i++)
							{
								Compile(FuncCallExp.Arguments[i]);

								if (i < FuncCallExp.Arguments.Count - 1)
									Append(", ");
							}

							AppendLine(");");*/

							Unindent();
							EmitRaw("# FuncCall END - {0}", FuncCallExp.Function.Identifier);
						}


						break;
					}

				default:
					{
						throw new NotImplementedException("Could not compile expression of type " + Ex.GetType());
					}
			}
		}
	}
}
