using System.Globalization;
using System.Numerics;
using System.Text;

namespace CTilde;

internal sealed partial class CEmitter
{
    private void EmitPreamble(CWriter writer)
    {
        writer.WriteLine(IsEspIdf
            ? "/* Generated by C~ draft 0.14 for ESP-IDF GNU C23. Do not edit. */"
            : "/* Generated by C~ draft 0.14 for GNU C23. Do not edit. */");
        writer.WriteLine("#include <stdbool.h>");
        writer.WriteLine("#include <stddef.h>");
        writer.WriteLine("#include <stdint.h>");
        writer.WriteLine("#include <inttypes.h>");
        writer.WriteLine("#include <stdio.h>");
        writer.WriteLine("#include <stdlib.h>");
        writer.WriteLine("#include <string.h>");
        if (_usesHostedIo)
        {
            writer.WriteLine("#include <errno.h>");
            writer.WriteLine("#if defined(_WIN32)\n#include <windows.h>\n#include <wchar.h>\n#endif");
        }
        writer.WriteLine("#include <limits.h>");
        writer.WriteLine("#include <float.h>");
        writer.WriteLine("#include <math.h>");
        writer.WriteLine("#if defined(_MSC_VER)\n#include <intrin.h>\n#endif");
        foreach (var header in EmittedTypes.Where(type => type.Kind == DeclaredTypeKind.Opaque).Select(type => type.NativeHeader!).Distinct(StringComparer.Ordinal).OrderBy(header => header, StringComparer.Ordinal))
            writer.WriteLine($"#include <{header}>");
        if (_nativeBufferTypes.Count != 0)
            writer.WriteLine("#if defined(_MSC_VER)\n#include <malloc.h>\n#endif");
        if (_usesExceptions)
            writer.WriteLine("#include <setjmp.h>");
        if (EmitDebugInstrumentation && !IsEspIdf)
            writer.WriteLine("#include <signal.h>");
        if (IsEspIdf)
            writer.WriteLine("#include \"ctilde_esp_shim.h\"");
        if (EmitDebugInstrumentation && IsEspIdf)
            writer.WriteLine("#include <esp_cpu.h>");
        writer.WriteLine();
        writer.WriteLine("#define CTILDE_RUNTIME_ABI_VERSION UINT32_C(14)");
        writer.WriteLine();
        writer.WriteLine("static_assert(CHAR_BIT == 8, \"C~ requires 8-bit bytes\");");
        writer.WriteLine("static_assert(sizeof(int32_t) == 4 && sizeof(uint32_t) == 4, \"C~ requires exact 32-bit integers\");");
        writer.WriteLine("static_assert(sizeof(int64_t) == 8 && sizeof(uint64_t) == 8, \"C~ requires exact 64-bit integers\");");
        if (_usesNativeIntegers)
        {
            writer.WriteLine("static_assert(sizeof(intptr_t) == sizeof(void*), \"C~ requires intptr_t to match pointer width\");");
            writer.WriteLine("static_assert(sizeof(uintptr_t) == sizeof(void*), \"C~ requires uintptr_t to match pointer width\");");
            writer.WriteLine("static_assert(sizeof(size_t) <= sizeof(uintptr_t), \"C~ requires nuint to represent size_t\");");
        }
        writer.WriteLine("static_assert(sizeof(float) == 4 && FLT_RADIX == 2 && FLT_MANT_DIG == 24, \"C~ requires IEEE-754 binary32 float\");");
        writer.WriteLine("static_assert(INT32_MIN == (-2147483647 - 1), \"C~ requires two's-complement int32_t\");");
        if (IsEspIdf)
            writer.WriteLine("static_assert(sizeof(void*) == 4, \"C~ ESP-IDF requires 32-bit pointers\");");
        writer.WriteLine();
        writer.WriteLine("#if defined(_MSC_VER)");
        writer.WriteLine("#define CT_NORETURN __declspec(noreturn)");
        writer.WriteLine("#pragma warning(disable: 4505) /* reachability may conservatively retain translation-local helpers */");
        writer.WriteLine("#elif defined(__GNUC__) || defined(__clang__)");
        writer.WriteLine("#define CT_NORETURN __attribute__((noreturn))");
        writer.WriteLine("#else");
        writer.WriteLine("#define CT_NORETURN _Noreturn");
        writer.WriteLine("#endif");
        writer.WriteLine("#if defined(__GNUC__) || defined(__clang__)");
        writer.WriteLine("#define CT_UNUSED __attribute__((unused))");
        writer.WriteLine("#else");
        writer.WriteLine("#define CT_UNUSED");
        writer.WriteLine("#endif");
        writer.WriteLine("#if defined(_MSC_VER)");
        writer.WriteLine("#define CT_FLEXIBLE_ARRAY 1");
        writer.WriteLine("#else");
        writer.WriteLine("#define CT_FLEXIBLE_ARRAY");
        writer.WriteLine("#endif");
        if (_nativeBufferTypes.Count != 0)
        {
            writer.WriteLine("#if defined(_MSC_VER)");
            writer.WriteLine("#define CT_ALLOCA(bytes) _alloca(bytes)");
            writer.WriteLine("#else");
            writer.WriteLine("#define CT_ALLOCA(bytes) __builtin_alloca(bytes)");
            writer.WriteLine("#endif");
        }
        writer.WriteLine();
        EmitAtomicRuntime(writer);
        writer.WriteLine();
        writer.WriteLine("typedef struct ct_vtable ct_vtable;");
        writer.WriteLine("typedef struct ct_type_descriptor ct_type_descriptor;");
        writer.WriteLine("typedef struct ct_panic_info { const char* Code; const char* File; int32_t Line; } ct_panic_info;");
        writer.WriteLine("typedef void (*ct_panic_handler)(const ct_panic_info* info, void* context);");
        writer.WriteLine("typedef struct ct_runtime_config { uint32_t Size; ct_panic_handler PanicHandler; void* PanicContext; } ct_runtime_config;");
        writer.WriteLine("typedef struct ct_module_descriptor { uint32_t AbiVersion; const char* Name; void (*Initialize)(void); void (*Finalize)(void); } ct_module_descriptor;");
        writer.WriteLine("static void ct_module_init(void);");
        writer.WriteLine("static void ct_module_fini(void);");
        writer.WriteLine("static ct_module_descriptor ct_program_module;");
        writer.WriteLine("typedef struct ct_object { const ct_type_descriptor* Type; uint32_t IdentityHash; ct_atomic_u32 RefCount; struct ct_object* ReleaseNext; } ct_object;");
        if (EmitDebugInformation)
        {
            writer.WriteLine("#if defined(_MSC_VER)");
            writer.WriteLine("#define CT_DEBUG_NOINLINE __declspec(noinline)");
            writer.WriteLine("#else");
            writer.WriteLine("#define CT_DEBUG_NOINLINE __attribute__((noinline, used))");
            writer.WriteLine("#endif");
            writer.WriteLine(EmitDebugInstrumentation ? "#define CT_DEBUG_USER_NOINLINE CT_DEBUG_NOINLINE" : "#define CT_DEBUG_USER_NOINLINE");
            writer.WriteLine("static volatile uintptr_t ct_debug_probe_sink;");
            writer.WriteLine("CT_DEBUG_NOINLINE void ct_debug_throw_hook(ct_object* exception, const char* code, const char* file, int line, uint32_t unhandled);");
            writer.WriteLine("CT_DEBUG_NOINLINE void ct_debug_fatal_hook(const char* code, const char* file, int line);");
            if (!EmitDebugInstrumentation)
            {
                writer.WriteLine("CT_DEBUG_NOINLINE void ct_debug_throw_hook(ct_object* exception, const char* code, const char* file, int line, uint32_t unhandled) { ct_debug_probe_sink = (uintptr_t)(void*)exception ^ (uintptr_t)(unsigned int)line ^ (uintptr_t)unhandled; (void)code; (void)file; }");
                writer.WriteLine("CT_DEBUG_NOINLINE void ct_debug_fatal_hook(const char* code, const char* file, int line) { ct_debug_probe_sink = (uintptr_t)(unsigned int)line; (void)code; (void)file; }");
            }
        }
        if (EmitDebugInstrumentation)
        {
            var enabledWords = Math.Max(1, (_debugSites.Count + 31) / 32);
            writer.WriteLine("enum { CT_DEBUG_REASON_SITE = 1u, CT_DEBUG_REASON_THROW = 2u, CT_DEBUG_REASON_FATAL = 3u, CT_DEBUG_REASON_ALLOC = 4u, CT_DEBUG_REASON_RELEASE = 5u, CT_DEBUG_REASON_LEAK = 6u, CT_DEBUG_REASON_STARTUP = 7u };");
            writer.WriteLine("enum { CT_DEBUG_EVENT_THROW = 1u, CT_DEBUG_EVENT_UNHANDLED = 2u, CT_DEBUG_EVENT_FATAL = 4u, CT_DEBUG_EVENT_ALLOC = 8u, CT_DEBUG_EVENT_RELEASE = 16u, CT_DEBUG_EVENT_LEAK = 32u, CT_DEBUG_EVENT_STARTUP = 64u };");
            writer.WriteLine($"typedef struct ct_debug_control_block {{ uint32_t Magic; uint32_t SiteCount; volatile uint32_t SessionActive; volatile uint32_t StartupReleased; volatile uint32_t EventMask; volatile uint32_t StepMode; volatile uint32_t StepDepth; volatile uintptr_t SelectedThread; volatile uintptr_t CurrentThread; volatile uintptr_t CurrentActivation; volatile uint32_t CurrentSite; volatile uint32_t CurrentReason; volatile uintptr_t CurrentObject; volatile uint32_t CurrentValue; volatile uintptr_t CurrentCode; volatile uintptr_t CurrentFile; volatile int32_t CurrentLine; volatile uint32_t Enabled[{enabledWords}]; }} ct_debug_control_block;");
            writer.WriteLine($"ct_debug_control_block ct_debug_control = {{ UINT32_C(0x43544432), UINT32_C({_debugSites.Count}), 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, UINT32_MAX, 0u, 0u, 0u, 0u, 0u, 0, {{0}} }};");
            writer.WriteLine("typedef struct ct_debug_runtime_summary_block { uint32_t LiveObjectCount; uint32_t TotalAllocations; uint32_t TotalFinalReleases; uint32_t QuarantineBlocks; uintptr_t QuarantineBytes; uint32_t CurrentSite; } ct_debug_runtime_summary_block;");
            writer.WriteLine("ct_debug_runtime_summary_block ct_debug_runtime_summary;");
            writer.WriteLine("static_assert(offsetof(ct_debug_control_block, SelectedThread) == (sizeof(uintptr_t) == 4u ? 28u : 32u), \"C~ debug control layout mismatch\");");
            writer.WriteLine("static_assert(offsetof(ct_debug_control_block, Enabled) == (sizeof(uintptr_t) == 4u ? 68u : 100u), \"C~ debug bitmap layout mismatch\");");
            writer.WriteLine("static_assert(offsetof(ct_debug_runtime_summary_block, QuarantineBytes) == 16u, \"C~ debug summary layout mismatch\");");
            writer.WriteLine("static ct_atomic_u32 ct_debug_stop_lock = CT_ATOMIC_U32_INIT(0u);");
            writer.WriteLine("typedef struct ct_debug_method_frame { void* State; struct ct_debug_method_frame* Previous; uintptr_t Activation; bool Active; } ct_debug_method_frame;");
            writer.WriteLine("CT_DEBUG_NOINLINE void ct_debug_site(uint32_t site);");
            writer.WriteLine("CT_DEBUG_NOINLINE void ct_debug_keep(void* storage);");
            writer.WriteLine("void ct_debug_method_enter(ct_debug_method_frame* frame);");
            writer.WriteLine("void ct_debug_method_leave(void* value);");
            writer.WriteLine("static void ct_debug_runtime_event(uint32_t reason, uint32_t mask, ct_object* object, uint32_t value, const char* code, const char* file, int32_t line);");
            if (IsEspIdf)
                writer.WriteLine("void ct_debug_wait_for_client(void);\nvoid ct_debug_startup_probe(void);");
            if (EmitDebugObjects)
            {
                writer.WriteLine("static void ct_debug_object_initialized(ct_object* object);");
                writer.WriteLine("static void ct_debug_arc_touch(ct_object* object);");
                writer.WriteLine("static void ct_debug_report_leaks(void);");
            }
        }
        writer.WriteLine("static_assert(sizeof(ct_atomic_u32) == sizeof(uint32_t), \"C~ atomic reference counts must remain 32-bit\");");
        writer.WriteLine("static_assert(_Alignof(ct_atomic_u32) == _Alignof(uint32_t), \"C~ atomic reference counts must preserve managed-header alignment\");");
        writer.WriteLine("typedef void (*ct_drop_value_fn)(void*);");
        writer.WriteLine("typedef struct ct_cleanup_record { struct ct_cleanup_record* Previous; void* Value; ct_drop_value_fn Drop; bool Active; } ct_cleanup_record;");
        if (_usesExceptions)
        {
            writer.WriteLine("typedef struct ct_exception_frame { jmp_buf* Target; struct ct_exception_frame* Previous; ct_cleanup_record* CleanupBoundary; } ct_exception_frame;");
            writer.WriteLine("CT_NORETURN static void ct_unhandled_exception(ct_object* exception);");
            writer.WriteLine("typedef enum ct_runtime_fault_kind { CT_FAULT_NULL, CT_FAULT_BOUNDS, CT_FAULT_DIVIDE, CT_FAULT_CAST, CT_FAULT_OVERFLOW, CT_FAULT_ARGUMENT, CT_FAULT_OUT_OF_MEMORY } ct_runtime_fault_kind;");
            writer.WriteLine("static bool ct_runtime_faults_ready;");
            writer.WriteLine("static void ct_runtime_faults_init(void);");
            writer.WriteLine("CT_NORETURN static void ct_raise_runtime_fault(ct_runtime_fault_kind kind, const char* code, const char* file, int line);");
        }
        writer.WriteLine("typedef struct ct_thread_state {");
        writer.WriteLine("    ct_cleanup_record* CleanupTop;");
        if (_usesExceptions)
        {
            writer.WriteLine("    ct_exception_frame* ExceptionTop;");
            writer.WriteLine("    ct_object* CurrentException;");
            writer.WriteLine("    const char* ExceptionCode;");
            writer.WriteLine("    const char* ExceptionFile;");
            writer.WriteLine("    int32_t ExceptionLine;");
        }
        writer.WriteLine("    ct_object* ReleaseHead;");
        writer.WriteLine("    bool ReleaseDraining;");
        writer.WriteLine("    bool HeapAllocated;");
        if (EmitDebugInstrumentation)
        {
            writer.WriteLine("    uint32_t DebugDepth;");
            writer.WriteLine("    uint32_t DebugCurrentSite;");
            writer.WriteLine("    uintptr_t DebugNextActivation;");
            writer.WriteLine("    ct_debug_method_frame* DebugFrameTop;");
        }
        writer.WriteLine("} ct_thread_state;");
        EmitThreadStorage(writer);
        writer.WriteLine("struct ct_type_descriptor { const char* Name; const ct_type_descriptor* Base; const ct_vtable* VTable; uint32_t TypeId; size_t Size; size_t Alignment; bool IsValue; void (*Drop)(ct_object*); };");
        writer.WriteLine("static ct_type_descriptor ct_desc_string;");
        writer.WriteLine("typedef struct ct_string { ct_object Object; int32_t Length; uint8_t Data[CT_FLEXIBLE_ARRAY]; } ct_string;");
        if (_usesNativeUtf8)
            writer.WriteLine("typedef struct ct_native_utf8_string { ct_string* Owner; const uint8_t* Data; size_t ByteLength; } ct_native_utf8_string;");
        writer.WriteLine("static struct { ct_object Object; int32_t Length; uint8_t Data[1]; } ct_empty_string_storage = { { &ct_desc_string, 0, CT_ATOMIC_U32_INIT(UINT32_MAX), NULL }, 0, { 0 } };");
        writer.WriteLine("static ct_string* const ct_empty_string = (ct_string*)(void*)&ct_empty_string_storage;");
        writer.WriteLine();
        writer.WriteLine("static ct_panic_handler ct_installed_panic_handler = NULL;");
        writer.WriteLine("static void* ct_installed_panic_context = NULL;");
        writer.WriteLine("CT_NORETURN static void ct_fail(const char* code, const char* file, int line)");
        writer.WriteLine("{");
        if (EmitDebugInformation)
            writer.WriteLine("    ct_debug_fatal_hook(code, file, line);");
        writer.WriteLine("    ct_panic_info info = { code, file, (int32_t)line };");
        writer.WriteLine("    if (ct_installed_panic_handler != NULL) ct_installed_panic_handler(&info, ct_installed_panic_context);");
        writer.WriteLine("    (void)fprintf(stderr, \"C~ runtime error %s at %s:%d\\n\", code, file, line);");
        writer.WriteLine(IsEspIdf ? "    abort();" : "    exit(EXIT_FAILURE);");
        writer.WriteLine("}");
        writer.WriteLine("static void* ct_require_nonnull(void* value, const char* file, int line) { if (value == NULL) ct_raise_runtime_fault(CT_FAULT_NULL, \"CTN0001\", file, line); return value; }");
        EmitPlatformAllocation(writer);
        EmitThreadRuntime(writer);
        if (EmitDebugInstrumentation)
            EmitInstrumentedDebugRuntime(writer);
        writer.WriteLine("#define ct_cleanup_top (ct_thread_require_attached()->CleanupTop)");
        if (_usesExceptions)
        {
            writer.WriteLine("#define ct_exception_top (ct_thread_require_attached()->ExceptionTop)");
            writer.WriteLine("#define ct_current_exception (ct_thread_require_attached()->CurrentException)");
        }
        writer.WriteLine("void ct_retain(ct_object* object)");
        writer.WriteLine("{");
        writer.WriteLine("    (void)ct_thread_require_attached();");
        writer.WriteLine("    if (object == NULL) return;");
        if (EmitDebugObjects)
            writer.WriteLine("    ct_debug_arc_touch(object);");
        writer.WriteLine("    uint32_t count = ct_atomic_load_relaxed(&object->RefCount);");
        writer.WriteLine("    for (;;)");
        writer.WriteLine("    {");
        writer.WriteLine("        if (count == UINT32_MAX) return;");
        writer.WriteLine("        if (count == 0u || count == UINT32_MAX - 1u) ct_fail(\"CTM0002\", \"<runtime>\", 0);");
        writer.WriteLine("        if (ct_atomic_compare_exchange_relaxed(&object->RefCount, &count, count + 1u)) return;");
        writer.WriteLine("    }");
        writer.WriteLine("}");
        writer.WriteLine("void ct_release(ct_object* object)");
        writer.WriteLine("{");
        writer.WriteLine("    ct_thread_state* state = ct_thread_require_attached();");
        writer.WriteLine("    if (object == NULL) return;");
        if (EmitDebugObjects)
            writer.WriteLine("    ct_debug_arc_touch(object);");
        writer.WriteLine("    uint32_t count = ct_atomic_load_relaxed(&object->RefCount);");
        writer.WriteLine("    for (;;)");
        writer.WriteLine("    {");
        writer.WriteLine("        if (count == UINT32_MAX) return;");
        writer.WriteLine("        if (count == 0u) ct_fail(\"CTM0003\", \"<runtime>\", 0);");
        writer.WriteLine("        if (ct_atomic_compare_exchange_release(&object->RefCount, &count, count - 1u)) break;");
        writer.WriteLine("    }");
        writer.WriteLine("    if (count != 1u) return;");
        writer.WriteLine("    ct_atomic_acquire_fence();");
        if (EmitDebugObjects)
            writer.WriteLine("    ct_debug_runtime_event(CT_DEBUG_REASON_RELEASE, CT_DEBUG_EVENT_RELEASE, object, 0u, NULL, NULL, 0);");
        writer.WriteLine("    object->ReleaseNext = state->ReleaseHead;");
        writer.WriteLine("    state->ReleaseHead = object;");
        writer.WriteLine("    if (state->ReleaseDraining) return;");
        writer.WriteLine("    state->ReleaseDraining = true;");
        writer.WriteLine("    while (state->ReleaseHead != NULL)");
        writer.WriteLine("    {");
        writer.WriteLine("        ct_object* current = state->ReleaseHead;");
        writer.WriteLine("        state->ReleaseHead = current->ReleaseNext;");
        writer.WriteLine("        current->ReleaseNext = NULL;");
        writer.WriteLine("        if (current->Type->Drop != NULL) current->Type->Drop(current);");
        writer.WriteLine("#if defined(CT_MEMORY_DIAGNOSTICS)");
        writer.WriteLine("        if (ct_atomic_fetch_sub_release(&ct_memory_live_objects, 1u) == 0u) ct_fail(\"CTM0003\", \"<runtime>\", 0);");
        writer.WriteLine("#endif");
        writer.WriteLine("        ct_dealloc(current);");
        writer.WriteLine("    }");
        writer.WriteLine("    state->ReleaseDraining = false;");
        writer.WriteLine("}");
        writer.WriteLine("static void ct_retain_ref_value(void* value) { ct_retain(*(ct_object**)value); }");
        writer.WriteLine("static void ct_drop_ref_value(void* value) { ct_object* object = *(ct_object**)value; *(ct_object**)value = NULL; ct_release(object); }");
        if (_usesNativeUtf8)
        {
            writer.WriteLine("static void ct_retain_value_nu8(void* storage) { ct_native_utf8_string* value = (ct_native_utf8_string*)storage; ct_retain((ct_object*)(void*)value->Owner); }");
            writer.WriteLine("static void ct_drop_value_nu8(void* storage) { ct_native_utf8_string* value = (ct_native_utf8_string*)storage; ct_string* owner = value->Owner; value->Owner = NULL; value->Data = NULL; value->ByteLength = 0u; ct_release((ct_object*)(void*)owner); }");
            writer.WriteLine("ct_native_utf8_string ct_native_utf8_borrow(ct_string* value) { (void)ct_require_nonnull(value, \"<native-utf8>\", 0); if (memchr(value->Data, 0, (size_t)value->Length) != NULL) ct_raise_runtime_fault(CT_FAULT_ARGUMENT, \"CTS0003\", \"<native-utf8>\", 0); ct_retain((ct_object*)(void*)value); return (ct_native_utf8_string){ value, value->Data, (size_t)value->Length }; }");
            writer.WriteLine("ct_native_utf8_string ct_native_utf8_null(void) { return (ct_native_utf8_string){ NULL, NULL, 0u }; }");
        }
        writer.WriteLine("static void ct_cleanup_push(ct_cleanup_record* record, void* value, ct_drop_value_fn drop) { record->Previous = ct_cleanup_top; record->Value = value; record->Drop = drop; record->Active = true; ct_cleanup_top = record; }");
        writer.WriteLine("static void ct_cleanup_unwind_to(ct_cleanup_record* boundary) { while (ct_cleanup_top != boundary) { ct_cleanup_record* record = ct_cleanup_top; if (record == NULL) ct_fail(\"CTM0003\", \"<runtime>\", 0); ct_cleanup_top = record->Previous; if (record->Active) { record->Active = false; record->Drop(record->Value); } } }");
        writer.WriteLine("static void ct_cleanup_disarm(ct_cleanup_record* record) { record->Active = false; }");
        if (_usesExceptions)
        {
            writer.WriteLine("CT_NORETURN static void ct_throw_core(ct_object* exception, const char* code, const char* file, int line)");
            writer.WriteLine("{");
            writer.WriteLine("    ct_thread_state* state = ct_thread_require_attached();");
            writer.WriteLine("    state->ExceptionCode = code; state->ExceptionFile = file; state->ExceptionLine = (int32_t)line;");
            if (EmitDebugInformation)
                writer.WriteLine("    ct_debug_throw_hook(exception, code, file, line, ct_exception_top == NULL ? 1u : 0u);");
            writer.WriteLine("    if (ct_exception_top == NULL) { ct_retain(exception); ct_cleanup_unwind_to(NULL); ct_unhandled_exception(exception); }");
            writer.WriteLine("    ct_retain(exception);");
            writer.WriteLine("    ct_release(ct_current_exception);");
            writer.WriteLine("    ct_current_exception = exception;");
            writer.WriteLine("    ct_exception_frame* target = ct_exception_top;");
            writer.WriteLine("    ct_cleanup_unwind_to(target->CleanupBoundary);");
            writer.WriteLine("    longjmp(*target->Target, 1);");
            writer.WriteLine("}");
            writer.WriteLine("CT_NORETURN static CT_UNUSED void ct_throw(ct_object* exception, const char* file, int line) { if (exception == NULL) ct_raise_runtime_fault(CT_FAULT_NULL, \"CTE0002\", file, line); ct_throw_core(exception, \"CTE0001\", file, line); }");
            writer.WriteLine("CT_NORETURN static CT_UNUSED void ct_rethrow(ct_object* exception) { ct_thread_state* state = ct_thread_require_attached(); ct_throw_core(exception, state->ExceptionCode, state->ExceptionFile, state->ExceptionLine); }");
        }
        writer.WriteLine("static ct_atomic_u32 ct_next_identity = CT_ATOMIC_U32_INIT(1u);");
        writer.WriteLine("static void ct_init_object(void* value, const ct_type_descriptor* type)");
        writer.WriteLine("{");
        writer.WriteLine("    ct_object* object = (ct_object*)value;");
        writer.WriteLine("    uint32_t identity;");
        writer.WriteLine("    do { identity = ct_atomic_fetch_add_relaxed(&ct_next_identity, 1u); } while (identity == 0u);");
        writer.WriteLine("    object->Type = type; object->IdentityHash = identity; ct_atomic_store_relaxed(&object->RefCount, 1u); object->ReleaseNext = NULL;");
        if (EmitDebugObjects)
            writer.WriteLine("    ct_debug_object_initialized(object);");
        writer.WriteLine("#if defined(CT_MEMORY_DIAGNOSTICS)");
        writer.WriteLine("    (void)ct_atomic_fetch_add_relaxed(&ct_memory_live_objects, 1u);");
        writer.WriteLine("#endif");
        writer.WriteLine("}");
        writer.WriteLine("static void ct_drop_string(ct_object* object) { ct_string* value = (ct_string*)(void*)object; value->Length = 0; }");
        writer.WriteLine("static size_t ct_flexible_allocation_size(size_t count, size_t element_size, size_t data_offset, size_t minimum_size, const char* file, int line)");
        writer.WriteLine("{");
        writer.WriteLine("    if (element_size != 0u && count > (SIZE_MAX - data_offset) / element_size) ct_raise_runtime_fault(CT_FAULT_OVERFLOW, \"CTA0002\", file, line);");
        writer.WriteLine("    size_t size = data_offset + count * element_size;");
        writer.WriteLine("    return size < minimum_size ? minimum_size : size;");
        writer.WriteLine("}");
        writer.WriteLine("static void ct_bounds(int32_t index, int32_t length, const char* file, int line) { if (index < 0 || index >= length) ct_raise_runtime_fault(CT_FAULT_BOUNDS, \"CTA0003\", file, line); }");
        if (_nativeBufferTypes.Count != 0)
        {
            writer.WriteLine("static void ct_native_bounds(size_t index, size_t length, const char* file, int line) { if (index >= length) ct_raise_runtime_fault(CT_FAULT_BOUNDS, \"CTB0001\", file, line); }");
            writer.WriteLine("static size_t ct_stack_bytes(size_t count, size_t element_size, const char* file, int line) { if (element_size != 0u && count > SIZE_MAX / element_size) ct_raise_runtime_fault(CT_FAULT_OVERFLOW, \"CTB0003\", file, line); return count * element_size; }");
        }
        writer.WriteLine("static int32_t ct_i32_bits(uint32_t value) { int32_t result; (void)memcpy(&result, &value, sizeof(result)); return result; }");
        writer.WriteLine("static int32_t ct_i32_add(int32_t a, int32_t b) { return ct_i32_bits((uint32_t)a + (uint32_t)b); }");
        writer.WriteLine("static int32_t ct_i32_sub(int32_t a, int32_t b) { return ct_i32_bits((uint32_t)a - (uint32_t)b); }");
        writer.WriteLine("static int32_t ct_i32_mul(int32_t a, int32_t b) { return ct_i32_bits((uint32_t)a * (uint32_t)b); }");
        writer.WriteLine("static int32_t ct_i32_neg(int32_t value) { return ct_i32_bits(0u - (uint32_t)value); }");
        writer.WriteLine("static int32_t ct_i32_div(int32_t a, int32_t b, const char* file, int line) { if (b == 0) ct_raise_runtime_fault(CT_FAULT_DIVIDE, \"CTI0001\", file, line); if (a == INT32_MIN && b == -1) return INT32_MIN; return a / b; }");
        writer.WriteLine("static int32_t ct_i32_mod(int32_t a, int32_t b, const char* file, int line) { if (b == 0) ct_raise_runtime_fault(CT_FAULT_DIVIDE, \"CTI0001\", file, line); if (a == INT32_MIN && b == -1) return 0; return a % b; }");
        writer.WriteLine("static uint32_t ct_u32_div(uint32_t a, uint32_t b, const char* file, int line) { if (b == 0u) ct_raise_runtime_fault(CT_FAULT_DIVIDE, \"CTI0001\", file, line); return a / b; }");
        writer.WriteLine("static uint32_t ct_u32_mod(uint32_t a, uint32_t b, const char* file, int line) { if (b == 0u) ct_raise_runtime_fault(CT_FAULT_DIVIDE, \"CTI0001\", file, line); return a % b; }");
        writer.WriteLine("static int32_t ct_i32_shl(int32_t a, int32_t b) { return ct_i32_bits((uint32_t)a << ((uint32_t)b & 31u)); }");
        writer.WriteLine("static int32_t ct_i32_shr(int32_t a, int32_t b) { uint32_t n = (uint32_t)b & 31u; if (n == 0u) return a; return a >= 0 ? (int32_t)((uint32_t)a >> n) : ct_i32_bits(((uint32_t)a >> n) | (~UINT32_C(0) << (32u - n))); }");
        writer.WriteLine("static int64_t ct_i64_bits(uint64_t value) { int64_t result; (void)memcpy(&result, &value, sizeof(result)); return result; }");
        writer.WriteLine("static int64_t ct_i64_add(int64_t a, int64_t b) { return ct_i64_bits((uint64_t)a + (uint64_t)b); }");
        writer.WriteLine("static int64_t ct_i64_sub(int64_t a, int64_t b) { return ct_i64_bits((uint64_t)a - (uint64_t)b); }");
        writer.WriteLine("static int64_t ct_i64_mul(int64_t a, int64_t b) { return ct_i64_bits((uint64_t)a * (uint64_t)b); }");
        writer.WriteLine("static int64_t ct_i64_neg(int64_t value) { return ct_i64_bits(UINT64_C(0) - (uint64_t)value); }");
        writer.WriteLine("static int64_t ct_i64_div(int64_t a, int64_t b, const char* file, int line) { if (b == 0) ct_raise_runtime_fault(CT_FAULT_DIVIDE, \"CTI0001\", file, line); if (a == INT64_MIN && b == -1) return INT64_MIN; return a / b; }");
        writer.WriteLine("static int64_t ct_i64_mod(int64_t a, int64_t b, const char* file, int line) { if (b == 0) ct_raise_runtime_fault(CT_FAULT_DIVIDE, \"CTI0001\", file, line); if (a == INT64_MIN && b == -1) return 0; return a % b; }");
        writer.WriteLine("static uint64_t ct_u64_div(uint64_t a, uint64_t b, const char* file, int line) { if (b == UINT64_C(0)) ct_raise_runtime_fault(CT_FAULT_DIVIDE, \"CTI0001\", file, line); return a / b; }");
        writer.WriteLine("static uint64_t ct_u64_mod(uint64_t a, uint64_t b, const char* file, int line) { if (b == UINT64_C(0)) ct_raise_runtime_fault(CT_FAULT_DIVIDE, \"CTI0001\", file, line); return a % b; }");
        writer.WriteLine("static int64_t ct_i64_shl(int64_t a, int32_t b) { return ct_i64_bits((uint64_t)a << ((uint32_t)b & 63u)); }");
        writer.WriteLine("static int64_t ct_i64_shr(int64_t a, int32_t b) { uint32_t n = (uint32_t)b & 63u; if (n == 0u) return a; return a >= 0 ? (int64_t)((uint64_t)a >> n) : ct_i64_bits(((uint64_t)a >> n) | (~UINT64_C(0) << (64u - n))); }");
        if (_usesNativeIntegers)
        {
            writer.WriteLine("static CT_UNUSED intptr_t ct_ni_bits(uintptr_t value) { intptr_t result; (void)memcpy(&result, &value, sizeof(result)); return result; }");
            writer.WriteLine("static CT_UNUSED intptr_t ct_ni_add(intptr_t a, intptr_t b) { return ct_ni_bits((uintptr_t)a + (uintptr_t)b); }");
            writer.WriteLine("static CT_UNUSED intptr_t ct_ni_sub(intptr_t a, intptr_t b) { return ct_ni_bits((uintptr_t)a - (uintptr_t)b); }");
            writer.WriteLine("static CT_UNUSED intptr_t ct_ni_mul(intptr_t a, intptr_t b) { return ct_ni_bits((uintptr_t)a * (uintptr_t)b); }");
            writer.WriteLine("static CT_UNUSED intptr_t ct_ni_neg(intptr_t value) { return ct_ni_bits((uintptr_t)0 - (uintptr_t)value); }");
            writer.WriteLine("static CT_UNUSED intptr_t ct_ni_div(intptr_t a, intptr_t b, const char* file, int line) { if (b == 0) ct_raise_runtime_fault(CT_FAULT_DIVIDE, \"CTI0001\", file, line); if (a == INTPTR_MIN && b == -1) return INTPTR_MIN; return a / b; }");
            writer.WriteLine("static CT_UNUSED intptr_t ct_ni_mod(intptr_t a, intptr_t b, const char* file, int line) { if (b == 0) ct_raise_runtime_fault(CT_FAULT_DIVIDE, \"CTI0001\", file, line); if (a == INTPTR_MIN && b == -1) return 0; return a % b; }");
            writer.WriteLine("static CT_UNUSED uintptr_t ct_nu_div(uintptr_t a, uintptr_t b, const char* file, int line) { if (b == (uintptr_t)0) ct_raise_runtime_fault(CT_FAULT_DIVIDE, \"CTI0001\", file, line); return a / b; }");
            writer.WriteLine("static CT_UNUSED uintptr_t ct_nu_mod(uintptr_t a, uintptr_t b, const char* file, int line) { if (b == (uintptr_t)0) ct_raise_runtime_fault(CT_FAULT_DIVIDE, \"CTI0001\", file, line); return a % b; }");
            writer.WriteLine("static CT_UNUSED intptr_t ct_ni_shl(intptr_t a, int32_t b) { const uint32_t mask = (uint32_t)(sizeof(uintptr_t) * CHAR_BIT - 1u); return ct_ni_bits((uintptr_t)a << ((uint32_t)b & mask)); }");
            writer.WriteLine("static CT_UNUSED intptr_t ct_ni_shr(intptr_t a, int32_t b) { const uint32_t width = (uint32_t)(sizeof(uintptr_t) * CHAR_BIT); uint32_t n = (uint32_t)b & (width - 1u); if (n == 0u) return a; return a >= 0 ? (intptr_t)((uintptr_t)a >> n) : ct_ni_bits(((uintptr_t)a >> n) | (~(uintptr_t)0 << (width - n))); }");
        }
        writer.WriteLine("static bool ct_string_equal(const ct_string* a, const ct_string* b) { if (a == b) return true; if (a == NULL || b == NULL || a->Length != b->Length) return false; return a->Length == 0 || memcmp(a->Data, b->Data, (size_t)a->Length) == 0; }");
        writer.WriteLine("static ct_string* ct_string_concat(const ct_string* a, const ct_string* b, const char* file, int line)");
        writer.WriteLine("{");
        writer.WriteLine("    if (a == NULL) a = ct_empty_string;");
        writer.WriteLine("    if (b == NULL) b = ct_empty_string;");
        writer.WriteLine("    if (a->Length > INT32_MAX - b->Length) ct_raise_runtime_fault(CT_FAULT_OVERFLOW, \"CTS0001\", file, line);");
        writer.WriteLine("    int32_t length = a->Length + b->Length;");
        writer.WriteLine("    ct_string* result = (ct_string*)ct_alloc(ct_flexible_allocation_size((size_t)length + 1u, 1u, offsetof(ct_string, Data), sizeof(ct_string), file, line), file, line);");
        writer.WriteLine("    ct_init_object(result, &ct_desc_string);");
        writer.WriteLine("    if (a->Length != 0) (void)memcpy(result->Data, a->Data, (size_t)a->Length);");
        writer.WriteLine("    if (b->Length != 0) (void)memcpy(result->Data + a->Length, b->Data, (size_t)b->Length);");
        writer.WriteLine("    result->Data[length] = 0;");
        writer.WriteLine("    result->Length = length;");
        writer.WriteLine("    return result;");
        writer.WriteLine("}");
        writer.WriteLine("static ct_string* ct_string_build(const uint8_t* const* parts, const int32_t* lengths, size_t count, const char* file, int line)");
        writer.WriteLine("{");
        writer.WriteLine("    int32_t length = 0;");
        writer.WriteLine("    for (size_t index = 0; index < count; index++) { if (lengths[index] < 0 || length > INT32_MAX - lengths[index]) ct_raise_runtime_fault(CT_FAULT_OVERFLOW, \"CTS0001\", file, line); length += lengths[index]; }");
        writer.WriteLine("    ct_string* result = (ct_string*)ct_alloc(ct_flexible_allocation_size((size_t)length + 1u, 1u, offsetof(ct_string, Data), sizeof(ct_string), file, line), file, line);");
        writer.WriteLine("    ct_init_object(result, &ct_desc_string);");
        writer.WriteLine("    size_t offset = 0u;");
        writer.WriteLine("    for (size_t index = 0; index < count; index++) { size_t segment = (size_t)lengths[index]; if (segment != 0u) (void)memcpy(result->Data + offset, parts[index], segment); offset += segment; }");
        writer.WriteLine("    result->Data[length] = 0;");
        writer.WriteLine("    result->Length = length;");
        writer.WriteLine("    return result;");
        writer.WriteLine("}");
        writer.WriteLine("static ct_string* ct_string_from_bytes(const uint8_t* source, int32_t length, const char* file, int line)");
        writer.WriteLine("{");
        writer.WriteLine("    if (length < 0) ct_raise_runtime_fault(CT_FAULT_OVERFLOW, \"CTS0002\", file, line);");
        writer.WriteLine("    ct_string* result = (ct_string*)ct_alloc(ct_flexible_allocation_size((size_t)length + 1u, 1u, offsetof(ct_string, Data), sizeof(ct_string), file, line), file, line);");
        writer.WriteLine("    ct_init_object(result, &ct_desc_string);");
        writer.WriteLine("    if (length > 0) (void)memcpy(result->Data, source, (size_t)length);");
        writer.WriteLine("    result->Data[length] = 0;");
        writer.WriteLine("    result->Length = length;");
        writer.WriteLine("    return result;");
        writer.WriteLine("}");
        writer.WriteLine("static ct_string* ct_string_from_format(const char* buffer, int length, size_t capacity, const char* file, int line)");
        writer.WriteLine("{");
        writer.WriteLine("    if (length < 0 || (size_t)length >= capacity) ct_raise_runtime_fault(CT_FAULT_OVERFLOW, \"CTS0002\", file, line);");
        writer.WriteLine("    return ct_string_from_bytes((const uint8_t*)buffer, (int32_t)length, file, line);");
        writer.WriteLine("}");
        writer.WriteLine("static ct_string* ct_to_string_int(int32_t value, const char* file, int line) { char buffer[12]; int length = snprintf(buffer, sizeof(buffer), \"%\" PRId32, value); return ct_string_from_format(buffer, length, sizeof(buffer), file, line); }");
        writer.WriteLine("static ct_string* ct_to_string_uint(uint32_t value, const char* file, int line) { char buffer[11]; int length = snprintf(buffer, sizeof(buffer), \"%\" PRIu32, value); return ct_string_from_format(buffer, length, sizeof(buffer), file, line); }");
        writer.WriteLine("static ct_string* ct_to_string_long(int64_t value, const char* file, int line) { char buffer[21]; int length = snprintf(buffer, sizeof(buffer), \"%\" PRId64, value); return ct_string_from_format(buffer, length, sizeof(buffer), file, line); }");
        writer.WriteLine("static ct_string* ct_to_string_ulong(uint64_t value, const char* file, int line) { char buffer[21]; int length = snprintf(buffer, sizeof(buffer), \"%\" PRIu64, value); return ct_string_from_format(buffer, length, sizeof(buffer), file, line); }");
        if (_usesNativeIntegers)
        {
            writer.WriteLine("static CT_UNUSED ct_string* ct_to_string_nint(intptr_t value, const char* file, int line) { char buffer[3 * sizeof(intptr_t) + 2]; int length = snprintf(buffer, sizeof(buffer), \"%\" PRIdPTR, value); return ct_string_from_format(buffer, length, sizeof(buffer), file, line); }");
            writer.WriteLine("static CT_UNUSED ct_string* ct_to_string_nuint(uintptr_t value, const char* file, int line) { char buffer[3 * sizeof(uintptr_t) + 1]; int length = snprintf(buffer, sizeof(buffer), \"%\" PRIuPTR, value); return ct_string_from_format(buffer, length, sizeof(buffer), file, line); }");
        }
        writer.WriteLine("static ct_string* ct_to_string_float(float value, const char* file, int line) { char buffer[32]; int length = snprintf(buffer, sizeof(buffer), \"%.9g\", (double)value); return ct_string_from_format(buffer, length, sizeof(buffer), file, line); }");
        writer.WriteLine("static ct_string* ct_to_string_bool(bool value, const char* file, int line) { const char* text = value ? \"True\" : \"False\"; return ct_string_from_bytes((const uint8_t*)text, value ? 4 : 5, file, line); }");
        writer.WriteLine("static ct_string* ct_to_string_char(uint8_t value, const char* file, int line) { return ct_string_from_bytes(&value, 1, file, line); }");
        if (IsEspIdf && EmitDebugInstrumentation)
        {
            writer.WriteLine("extern void esp_gdbstub_putchar(int value);");
            writer.WriteLine("extern void esp_gdbstub_flush(void);");
            writer.WriteLine("extern void esp_rom_uart_putc(char value);");
            writer.WriteLine("static void ct_debug_console_write(const char* data, size_t length);");
            writer.WriteLine("static void ct_debug_console_flush(void);");
            writer.WriteLine("void ct_write_string(ct_string* value) { if (value != NULL && value->Length > 0) ct_debug_console_write((const char*)value->Data, (size_t)value->Length); }");
            writer.WriteLine("void ct_write_char(uint8_t value) { char buffer[1] = { (char)value }; ct_debug_console_write(buffer, 1u); }");
            writer.WriteLine("void ct_write_int(int32_t value) { char buffer[12]; int length = snprintf(buffer, sizeof(buffer), \"%\" PRId32, value); if (length > 0) ct_debug_console_write(buffer, (size_t)length); }");
            writer.WriteLine("void ct_write_uint(uint32_t value) { char buffer[11]; int length = snprintf(buffer, sizeof(buffer), \"%\" PRIu32, value); if (length > 0) ct_debug_console_write(buffer, (size_t)length); }");
            writer.WriteLine("void ct_write_long(int64_t value) { char buffer[21]; int length = snprintf(buffer, sizeof(buffer), \"%\" PRId64, value); if (length > 0) ct_debug_console_write(buffer, (size_t)length); }");
            writer.WriteLine("void ct_write_ulong(uint64_t value) { char buffer[21]; int length = snprintf(buffer, sizeof(buffer), \"%\" PRIu64, value); if (length > 0) ct_debug_console_write(buffer, (size_t)length); }");
            if (_usesNativeIntegers)
            {
                writer.WriteLine("void ct_write_nint(intptr_t value) { char buffer[3 * sizeof(intptr_t) + 2]; int length = snprintf(buffer, sizeof(buffer), \"%\" PRIdPTR, value); if (length > 0) ct_debug_console_write(buffer, (size_t)length); }");
                writer.WriteLine("void ct_write_nuint(uintptr_t value) { char buffer[3 * sizeof(uintptr_t) + 1]; int length = snprintf(buffer, sizeof(buffer), \"%\" PRIuPTR, value); if (length > 0) ct_debug_console_write(buffer, (size_t)length); }");
            }
            writer.WriteLine("void ct_write_float(float value) { char buffer[32]; int length = snprintf(buffer, sizeof(buffer), \"%.9g\", (double)value); if (length > 0) ct_debug_console_write(buffer, (size_t)length); }");
            writer.WriteLine("void ct_write_bool(bool value) { const char* text = value ? \"True\" : \"False\"; ct_debug_console_write(text, value ? 4u : 5u); }");
            writer.WriteLine("void ct_write_line(void) { ct_debug_console_write(\"\\n\", 1u); ct_debug_console_flush(); }");
        }
        else
        {
            writer.WriteLine("void ct_write_string(ct_string* value) { if (value != NULL && value->Length > 0) (void)fwrite(value->Data, 1u, (size_t)value->Length, stdout); }");
            writer.WriteLine("void ct_write_char(uint8_t value) { (void)fputc((int)value, stdout); }");
            writer.WriteLine("void ct_write_int(int32_t value) { (void)fprintf(stdout, \"%\" PRId32, value); }");
            writer.WriteLine("void ct_write_uint(uint32_t value) { (void)fprintf(stdout, \"%\" PRIu32, value); }");
            writer.WriteLine("void ct_write_long(int64_t value) { (void)fprintf(stdout, \"%\" PRId64, value); }");
            writer.WriteLine("void ct_write_ulong(uint64_t value) { (void)fprintf(stdout, \"%\" PRIu64, value); }");
            if (_usesNativeIntegers)
            {
                writer.WriteLine("void ct_write_nint(intptr_t value) { (void)fprintf(stdout, \"%\" PRIdPTR, value); }");
                writer.WriteLine("void ct_write_nuint(uintptr_t value) { (void)fprintf(stdout, \"%\" PRIuPTR, value); }");
            }
            writer.WriteLine("void ct_write_float(float value) { (void)fprintf(stdout, \"%.9g\", (double)value); }");
            writer.WriteLine("void ct_write_bool(bool value) { (void)fputs(value ? \"True\" : \"False\", stdout); }");
            writer.WriteLine($"void ct_write_line(void) {{ (void)fputc('\\n', stdout);{(EmitDebugInstrumentation ? " (void)fflush(stdout);" : string.Empty)} }}");
        }
        if (!IsEspIdf)
            writer.WriteLine("void ct_environment_exit(int32_t code) { exit((int)code); }");
        writer.WriteLine();
    }

    private void EmitStringLiterals(CWriter writer)
    {
        foreach (var pair in _stringLiterals.OrderBy(pair => pair.Value))
        {
            var bytes = Encoding.UTF8.GetBytes(pair.Key);
            var values = bytes.Length == 0 ? "0" : string.Join(", ", bytes.Select(value => value.ToString(CultureInfo.InvariantCulture)).Append("0"));
            writer.WriteLine($"static struct {{ ct_object Object; int32_t Length; uint8_t Data[{bytes.Length + 1}]; }} ct_sl_{pair.Value} = {{ {{ &ct_desc_string, 0, CT_ATOMIC_U32_INIT(UINT32_MAX), NULL }}, {bytes.Length}, {{ {values} }} }};");
        }
        if (_stringLiterals.Count > 0)
            writer.WriteLine();
    }

    private void EmitForwardDeclarations(CWriter writer)
    {
        foreach (var type in _functionPointerTypes.OrderBy(type => NameMangler.TypeCode(type), StringComparer.Ordinal))
        {
            var signature = type.FunctionPointer!;
            var parameters = FunctionPointerParameters(signature);
            writer.WriteLine($"typedef {CTypeName(signature.ReturnType)} (*{CTypeName(type)})({parameters});");
        }
        if (_functionPointerTypes.Count != 0)
            writer.WriteLine();
        foreach (var buffer in _nativeBufferTypes.OrderBy(NameMangler.TypeCode, StringComparer.Ordinal))
        {
            var element = CTypeName(buffer.ElementType!);
            var pointer = buffer.Kind == CTypeKind.ReadOnlyNativeBuffer ? $"const {element}*" : $"{element}*";
            writer.WriteLine($"typedef struct {CTypeName(buffer)} {{ {pointer} Data; size_t Length; }} {CTypeName(buffer)};");
        }
        if (_nativeBufferTypes.Count != 0)
            writer.WriteLine();
        foreach (var type in EmittedTypes.Where(type => type.Kind is not DeclaredTypeKind.Enum and not DeclaredTypeKind.Opaque && type.FullName != "Esp.Idf.EspError"))
            writer.WriteLine($"typedef struct {NameMangler.Type(type)} {NameMangler.Type(type)};");
        foreach (var array in _arrayTypes.OrderBy(array => NameMangler.TypeCode(array), StringComparer.Ordinal))
            writer.WriteLine($"typedef struct {NameMangler.Array(array.ElementType!)} {NameMangler.Array(array.ElementType!)};");
        foreach (var type in OrderLayoutTypes().Where(type => type.Kind is DeclaredTypeKind.Class or DeclaredTypeKind.Delegate))
            writer.WriteLine($"static ct_type_descriptor {DescriptorName(type)};");
        foreach (var array in _arrayTypes.OrderBy(array => NameMangler.TypeCode(array), StringComparer.Ordinal))
            writer.WriteLine($"static ct_type_descriptor {ArrayDescriptorName(array.ElementType!)};");
        if (EmittedTypes.Any(type => type.Kind is not DeclaredTypeKind.Enum and not DeclaredTypeKind.Opaque && type.FullName != "Esp.Idf.EspError") || _arrayTypes.Count > 0)
            writer.WriteLine();
    }

    private void EmitTypeLayouts(CWriter writer)
    {
        foreach (var type in EmittedTypes.Where(type => type.Kind == DeclaredTypeKind.Enum))
        {
            var underlying = type.Fields.Single(field => field.Name == "<underlying>").Type;
            writer.WriteLine($"typedef {CTypeName(underlying)} {NameMangler.Type(type)};");
            foreach (var value in type.EnumValues)
                writer.WriteLine($"#define {NameMangler.Identifier(type.FullName + "." + value.Name)} (({NameMangler.Type(type)}){FormatIntegralConstant(value.Value, underlying)})");
            writer.WriteLine();
        }
        foreach (var type in OrderLayoutTypes())
        {
            writer.WriteLine($"struct {NameMangler.Type(type)}");
            writer.WriteLine("{");
            if (type.Kind == DeclaredTypeKind.Delegate)
            {
                var parameters = string.Concat(type.DelegateParameters.Select(parameter => $", {ParameterTypeName(parameter)}"));
                writer.WriteLine("    ct_object ct_header;");
                writer.WriteLine($"    {CTypeName(type.DelegateReturnType!)} (*ct_invoke)(ct_object*{parameters});");
                writer.WriteLine("    ct_object* ct_target;");
                writer.WriteLine("};");
                writer.WriteLine();
                continue;
            }
            var fields = type.Fields.Where(field => !field.IsStatic).ToArray();
            if (type.Kind == DeclaredTypeKind.Class)
            {
                if (type.IsObject)
                    writer.WriteLine("    ct_object ct_header;");
                else if (type.BaseType is not null)
                    writer.WriteLine($"    {NameMangler.Type(type.BaseType)} ct_base;");
            }
            else if (fields.Length == 0)
                writer.WriteLine("    uint8_t ct_empty;");
            foreach (var field in fields)
                writer.WriteLine($"    {CDeclaration(field.Type, field.CName)};");
            writer.WriteLine("};");
            writer.WriteLine();
        }
        if (Model.Types.TryGetValue("System.Object", out var objectType) && EmittedTypes.Contains(objectType))
            writer.WriteLine($"typedef {NameMangler.Type(objectType)} ct_managed_object;");
        writer.WriteLine();
    }

    private IEnumerable<TypeSymbol> OrderLayoutTypes()
    {
        var types = EmittedTypes.Where(type => type.Kind is not DeclaredTypeKind.Enum and not DeclaredTypeKind.Opaque && type.FullName != "Esp.Idf.EspError").ToArray();
        var emitted = new HashSet<TypeSymbol>();
        var visiting = new HashSet<TypeSymbol>();
        foreach (var type in types)
            foreach (var result in Visit(type))
                yield return result;

        IEnumerable<TypeSymbol> Visit(TypeSymbol type)
        {
            if (emitted.Contains(type))
                yield break;
            if (!visiting.Add(type))
                yield break;
            if (type.BaseType is not null)
                foreach (var result in Visit(type.BaseType))
                    yield return result;
            foreach (var dependency in type.Fields.Where(field => !field.IsStatic && field.Type.Kind == CTypeKind.Struct).Select(field => field.Type.Symbol!).Distinct())
                foreach (var result in Visit(dependency))
                    yield return result;
            visiting.Remove(type);
            if (emitted.Add(type))
                yield return type;
        }
    }

    private void EmitArrayLayouts(CWriter writer)
    {
        foreach (var array in _arrayTypes.OrderBy(array => NameMangler.TypeCode(array), StringComparer.Ordinal))
        {
            var name = NameMangler.Array(array.ElementType!);
            writer.WriteLine($"struct {name} {{ ct_object Object; int32_t Length; {CTypeName(array.ElementType!)} Data[CT_FLEXIBLE_ARRAY]; }};");
            writer.WriteLine($"static {name}* ct_new_{name}(int32_t length, const char* file, int line) {{ if (length < 0) ct_raise_runtime_fault(CT_FAULT_OVERFLOW, \"CTA0001\", file, line); size_t size = ct_flexible_allocation_size((size_t)length, sizeof({CTypeName(array.ElementType!)}), offsetof({name}, Data), sizeof({name}), file, line); {name}* value = ({name}*)ct_alloc(size, file, line); ct_init_object(value, &{ArrayDescriptorName(array.ElementType!)}); value->Length = length; return value; }}");
        }
        if (_arrayTypes.Count > 0)
            writer.WriteLine();
    }

    private void EmitPlatformAllocation(CWriter writer)
    {
        writer.WriteLine("#if defined(CTILDE_CONFORMANCE)");
        writer.WriteLine("static int32_t ct_test_allocation_failure_countdown = -1;");
        writer.WriteLine("void ct_runtime_test_fail_allocation_after(int32_t successful_allocations) { ct_test_allocation_failure_countdown = successful_allocations; }");
        writer.WriteLine("#endif");
        writer.WriteLine("#if defined(CT_MEMORY_DIAGNOSTICS)");
        writer.WriteLine("static ct_atomic_u32 ct_memory_live_allocations = CT_ATOMIC_U32_INIT(0u);");
        writer.WriteLine("static ct_atomic_u32 ct_memory_live_objects = CT_ATOMIC_U32_INIT(0u);");
        writer.WriteLine("static ct_atomic_u32 ct_memory_total_allocations = CT_ATOMIC_U32_INIT(0u);");
        writer.WriteLine("uint32_t ct_memory_diagnostic_live_allocations(void) { return ct_atomic_load_relaxed(&ct_memory_live_allocations); }");
        writer.WriteLine("uint32_t ct_memory_diagnostic_live_objects(void) { return ct_atomic_load_relaxed(&ct_memory_live_objects); }");
        writer.WriteLine("uint32_t ct_memory_diagnostic_total_allocations(void) { return ct_atomic_load_relaxed(&ct_memory_total_allocations); }");
        writer.WriteLine("#endif");
        if (EmitDebugObjects)
        {
            writer.WriteLine("#if defined(_MSC_VER)");
            writer.WriteLine("typedef __declspec(align(16)) struct ct_debug_allocation { struct ct_debug_allocation* Previous; struct ct_debug_allocation* Next; size_t Size; const char* File; int32_t Line; ct_atomic_u32 LastSite; uint64_t AlignmentPadding; } ct_debug_allocation;");
            writer.WriteLine("#else");
            writer.WriteLine("typedef struct __attribute__((aligned(__alignof__(max_align_t)))) ct_debug_allocation { struct ct_debug_allocation* Previous; struct ct_debug_allocation* Next; size_t Size; const char* File; int32_t Line; ct_atomic_u32 LastSite; } ct_debug_allocation;");
            writer.WriteLine("#endif");
            writer.WriteLine("static ct_debug_allocation* ct_debug_live_head = NULL;");
            writer.WriteLine("static ct_debug_allocation* ct_debug_quarantine_head = NULL;");
            writer.WriteLine("static ct_debug_allocation* ct_debug_quarantine_tail = NULL;");
            writer.WriteLine("static size_t ct_debug_quarantine_bytes = 0u;");
            writer.WriteLine("static uint32_t ct_debug_quarantine_count = 0u;");
            writer.WriteLine("static ct_atomic_u32 ct_debug_registry_lock = CT_ATOMIC_U32_INIT(0u);");
            writer.WriteLine("static ct_atomic_u32 ct_debug_live_count = CT_ATOMIC_U32_INIT(0u);");
            writer.WriteLine("static ct_atomic_u32 ct_debug_allocation_count = CT_ATOMIC_U32_INIT(0u);");
            writer.WriteLine("static ct_atomic_u32 ct_debug_final_release_count = CT_ATOMIC_U32_INIT(0u);");
            writer.WriteLine("static ct_debug_allocation* ct_debug_allocation_for(void* value) { return value == NULL ? NULL : ((ct_debug_allocation*)value) - 1; }");
            writer.WriteLine("static void ct_debug_registry_acquire(void) { uint32_t expected; do { expected = 0u; } while (!ct_atomic_compare_exchange_relaxed(&ct_debug_registry_lock, &expected, 1u)); ct_atomic_acquire_fence(); }");
            writer.WriteLine("static void ct_debug_registry_release(void) { ct_atomic_store_release(&ct_debug_registry_lock, 0u); }");
            writer.WriteLine("static void ct_debug_native_free(ct_debug_allocation* allocation) { free(allocation); }");
        }
        writer.WriteLine("static void* ct_alloc(size_t size, const char* file, int line) {");
        writer.WriteLine("#if defined(CTILDE_CONFORMANCE)");
        writer.WriteLine("    if (ct_test_allocation_failure_countdown == 0) ct_raise_runtime_fault(CT_FAULT_OUT_OF_MEMORY, \"CTM0001\", file, line);");
        writer.WriteLine("    if (ct_test_allocation_failure_countdown > 0) --ct_test_allocation_failure_countdown;");
        writer.WriteLine("#endif");
        if (EmitDebugObjects)
        {
            writer.WriteLine("    size_t payload = size == 0u ? 1u : size;");
            writer.WriteLine($"    size_t guard = {(EmitDebugGuards ? "sizeof(uint32_t)" : "0u")}; if (payload > SIZE_MAX - sizeof(ct_debug_allocation) - guard) ct_fail(\"CTM0001\", file, line);");
            writer.WriteLine("    ct_debug_allocation* allocation = (ct_debug_allocation*)calloc(1u, sizeof(ct_debug_allocation) + payload + guard); void* value = allocation == NULL ? NULL : (void*)(allocation + 1);");
            writer.WriteLine("    if (value != NULL) { allocation->Size = payload; allocation->File = file; allocation->Line = (int32_t)line; ct_atomic_store_relaxed(&allocation->LastSite, UINT32_MAX); ct_debug_registry_acquire(); allocation->Next = ct_debug_live_head; if (ct_debug_live_head != NULL) ct_debug_live_head->Previous = allocation; ct_debug_live_head = allocation; ct_debug_registry_release(); (void)ct_atomic_fetch_add_relaxed(&ct_debug_live_count, 1u); (void)ct_atomic_fetch_add_relaxed(&ct_debug_allocation_count, 1u); }");
            if (EmitDebugGuards)
                writer.WriteLine("    if (value != NULL) { uint32_t canary = UINT32_C(0xC71DE14D); (void)memcpy((uint8_t*)value + payload, &canary, sizeof(canary)); }");
            writer.WriteLine("    if (value == NULL) { if (ct_runtime_faults_ready && ct_thread_current() != NULL) ct_raise_runtime_fault(CT_FAULT_OUT_OF_MEMORY, \"CTM0001\", file, line); ct_fail(\"CTM0001\", file, line); }");
        }
        else
            writer.WriteLine("    void* value = calloc(1u, size == 0u ? 1u : size); if (value == NULL) { if (ct_runtime_faults_ready && ct_thread_current() != NULL) ct_raise_runtime_fault(CT_FAULT_OUT_OF_MEMORY, \"CTM0001\", file, line); ct_fail(\"CTM0001\", file, line); }");
        writer.WriteLine("#if defined(CT_MEMORY_DIAGNOSTICS)");
        writer.WriteLine("    (void)ct_atomic_fetch_add_relaxed(&ct_memory_live_allocations, 1u);");
        writer.WriteLine("    (void)ct_atomic_fetch_add_relaxed(&ct_memory_total_allocations, 1u);");
        writer.WriteLine("#endif");
        writer.WriteLine("    return value; }");
        writer.WriteLine("static void ct_dealloc(void* value) { if (value == NULL) return;");
        writer.WriteLine("#if defined(CT_MEMORY_DIAGNOSTICS)");
        writer.WriteLine("    if (ct_atomic_fetch_sub_release(&ct_memory_live_allocations, 1u) == 0u) ct_fail(\"CTM0003\", \"<runtime>\", 0);");
        writer.WriteLine("#endif");
        if (EmitDebugObjects)
        {
            writer.WriteLine("    ct_debug_allocation* allocation = ct_debug_allocation_for(value);");
            if (EmitDebugGuards)
                writer.WriteLine("    uint32_t canary = 0u; (void)memcpy(&canary, (uint8_t*)value + allocation->Size, sizeof(canary)); if (canary != UINT32_C(0xC71DE14D)) ct_fail(\"CTM0004\", allocation->File, allocation->Line);");
            writer.WriteLine("    ct_debug_registry_acquire(); if (allocation->Previous != NULL) allocation->Previous->Next = allocation->Next; else ct_debug_live_head = allocation->Next; if (allocation->Next != NULL) allocation->Next->Previous = allocation->Previous; allocation->Previous = NULL; allocation->Next = NULL; ct_debug_registry_release();");
            writer.WriteLine("    if (ct_atomic_fetch_sub_release(&ct_debug_live_count, 1u) == 0u) ct_fail(\"CTM0003\", \"<debug-registry>\", 0);");
            writer.WriteLine("    (void)ct_atomic_fetch_add_relaxed(&ct_debug_final_release_count, 1u);");
            if (EmitDebugGuards)
            {
                writer.WriteLine("    (void)memset(value, 0xDD, allocation->Size); ct_debug_registry_acquire(); allocation->Previous = ct_debug_quarantine_tail; if (ct_debug_quarantine_tail != NULL) ct_debug_quarantine_tail->Next = allocation; else ct_debug_quarantine_head = allocation; ct_debug_quarantine_tail = allocation; ++ct_debug_quarantine_count; ct_debug_quarantine_bytes += allocation->Size; while (ct_debug_quarantine_count > 16u || ct_debug_quarantine_bytes > 32768u) { ct_debug_allocation* oldest = ct_debug_quarantine_head; ct_debug_quarantine_head = oldest->Next; if (ct_debug_quarantine_head != NULL) ct_debug_quarantine_head->Previous = NULL; else ct_debug_quarantine_tail = NULL; --ct_debug_quarantine_count; ct_debug_quarantine_bytes -= oldest->Size; ct_debug_native_free(oldest); } ct_debug_registry_release();");
            }
            else
                writer.WriteLine("    ct_debug_native_free(allocation);");
            writer.WriteLine("}");
        }
        else
            writer.WriteLine("    free(value); }");
    }

    private static void EmitAtomicRuntime(CWriter writer)
    {
        writer.WriteLine("#if defined(_MSC_VER)");
        writer.WriteLine("typedef volatile long ct_atomic_u32;");
        writer.WriteLine("#define CT_ATOMIC_U32_INIT(value) ((ct_atomic_u32)(value))");
        writer.WriteLine("static uint32_t ct_atomic_load_relaxed(const ct_atomic_u32* value) { return (uint32_t)_InterlockedCompareExchange((volatile long*)value, 0, 0); }");
        writer.WriteLine("static uint32_t ct_atomic_load_acquire(const ct_atomic_u32* value) { return (uint32_t)_InterlockedCompareExchange((volatile long*)value, 0, 0); }");
        writer.WriteLine("static void ct_atomic_store_relaxed(ct_atomic_u32* value, uint32_t desired) { (void)_InterlockedExchange(value, (long)desired); }");
        writer.WriteLine("static void ct_atomic_store_release(ct_atomic_u32* value, uint32_t desired) { (void)_InterlockedExchange(value, (long)desired); }");
        writer.WriteLine("static bool ct_atomic_compare_exchange_relaxed(ct_atomic_u32* value, uint32_t* expected, uint32_t desired) { long observed = _InterlockedCompareExchange(value, (long)desired, (long)*expected); if ((uint32_t)observed == *expected) return true; *expected = (uint32_t)observed; return false; }");
        writer.WriteLine("static bool ct_atomic_compare_exchange_release(ct_atomic_u32* value, uint32_t* expected, uint32_t desired) { return ct_atomic_compare_exchange_relaxed(value, expected, desired); }");
        writer.WriteLine("static uint32_t ct_atomic_fetch_add_relaxed(ct_atomic_u32* value, uint32_t amount) { return (uint32_t)_InterlockedExchangeAdd(value, (long)amount); }");
        writer.WriteLine("static uint32_t ct_atomic_fetch_sub_release(ct_atomic_u32* value, uint32_t amount) { return (uint32_t)_InterlockedExchangeAdd(value, -(long)amount); }");
        writer.WriteLine("static void ct_atomic_acquire_fence(void) { _ReadWriteBarrier(); }");
        writer.WriteLine("#else");
        writer.WriteLine("typedef uint32_t ct_atomic_u32;");
        writer.WriteLine("#define CT_ATOMIC_U32_INIT(value) ((ct_atomic_u32)(value))");
        writer.WriteLine("static uint32_t ct_atomic_load_relaxed(const ct_atomic_u32* value) { return __atomic_load_n(value, __ATOMIC_RELAXED); }");
        writer.WriteLine("static uint32_t ct_atomic_load_acquire(const ct_atomic_u32* value) { return __atomic_load_n(value, __ATOMIC_ACQUIRE); }");
        writer.WriteLine("static void ct_atomic_store_relaxed(ct_atomic_u32* value, uint32_t desired) { __atomic_store_n(value, desired, __ATOMIC_RELAXED); }");
        writer.WriteLine("static void ct_atomic_store_release(ct_atomic_u32* value, uint32_t desired) { __atomic_store_n(value, desired, __ATOMIC_RELEASE); }");
        writer.WriteLine("static bool ct_atomic_compare_exchange_relaxed(ct_atomic_u32* value, uint32_t* expected, uint32_t desired) { return __atomic_compare_exchange_n(value, expected, desired, true, __ATOMIC_RELAXED, __ATOMIC_RELAXED); }");
        writer.WriteLine("static bool ct_atomic_compare_exchange_release(ct_atomic_u32* value, uint32_t* expected, uint32_t desired) { return __atomic_compare_exchange_n(value, expected, desired, true, __ATOMIC_RELEASE, __ATOMIC_RELAXED); }");
        writer.WriteLine("static uint32_t ct_atomic_fetch_add_relaxed(ct_atomic_u32* value, uint32_t amount) { return __atomic_fetch_add(value, amount, __ATOMIC_RELAXED); }");
        writer.WriteLine("static uint32_t ct_atomic_fetch_sub_release(ct_atomic_u32* value, uint32_t amount) { return __atomic_fetch_sub(value, amount, __ATOMIC_RELEASE); }");
        writer.WriteLine("static void ct_atomic_acquire_fence(void) { __atomic_thread_fence(__ATOMIC_ACQUIRE); }");
        writer.WriteLine("#endif");
    }

    private void EmitThreadStorage(CWriter writer)
    {
        if (IsEspIdf)
        {
            writer.WriteLine("static void ct_thread_state_deleted(int index, void* value);");
            writer.WriteLine("static ct_thread_state* ct_thread_current(void) { return (ct_thread_state*)ct_esp_thread_state_get(); }");
            writer.WriteLine("static void ct_thread_set_current(ct_thread_state* state) { ct_esp_thread_state_set(state, state == NULL ? NULL : ct_thread_state_deleted); }");
        }
        else
        {
            writer.WriteLine("#if defined(_MSC_VER)");
            writer.WriteLine("static __declspec(thread) ct_thread_state* ct_thread_current_state = NULL;");
            writer.WriteLine("#else");
            writer.WriteLine("static _Thread_local ct_thread_state* ct_thread_current_state = NULL;");
            writer.WriteLine("#endif");
            writer.WriteLine("static ct_thread_state* ct_thread_current(void) { return ct_thread_current_state; }");
            writer.WriteLine("static void ct_thread_set_current(ct_thread_state* state) { ct_thread_current_state = state; }");
        }
    }

    private void EmitThreadRuntime(CWriter writer)
    {
        writer.WriteLine("enum { CT_RUNTIME_UNINITIALIZED = 0u, CT_RUNTIME_INITIALIZING = 1u, CT_RUNTIME_READY = 2u, CT_RUNTIME_SHUTTING_DOWN = 3u };");
        writer.WriteLine("static ct_atomic_u32 ct_runtime_phase = CT_ATOMIC_U32_INIT(CT_RUNTIME_UNINITIALIZED);");
        writer.WriteLine("static ct_atomic_u32 ct_attached_thread_count = CT_ATOMIC_U32_INIT(0u);");
        writer.WriteLine("static ct_thread_state ct_primary_thread_state;");
        writer.WriteLine("static ct_thread_state* ct_thread_require_attached(void) { ct_thread_state* state = ct_thread_current(); if (state == NULL) ct_fail(\"CTT0001\", \"<native-entry>\", 0); return state; }");
        writer.WriteLine("static void ct_runtime_require_ready(void) { (void)ct_thread_require_attached(); if (ct_atomic_load_acquire(&ct_runtime_phase) != CT_RUNTIME_READY) ct_fail(\"CTT0002\", \"<native-entry>\", 0); }");
        if (IsEspIdf)
            writer.WriteLine("static void ct_thread_state_deleted(int index, void* value) { (void)index; (void)value; ct_fail(\"CTT0002\", \"<thread-exit>\", 0); }");
        writer.WriteLine("static void ct_thread_attach_primary(ct_thread_state* state)");
        writer.WriteLine("{");
        writer.WriteLine("    uint32_t expected = CT_RUNTIME_UNINITIALIZED;");
        writer.WriteLine("    if (state == NULL || ct_thread_current() != NULL || !ct_atomic_compare_exchange_relaxed(&ct_runtime_phase, &expected, CT_RUNTIME_INITIALIZING)) ct_fail(\"CTT0002\", \"<thread-attach>\", 0);");
        writer.WriteLine("    (void)memset(state, 0, sizeof(*state));");
        writer.WriteLine("    ct_thread_set_current(state);");
        writer.WriteLine("    ct_atomic_store_relaxed(&ct_attached_thread_count, 1u);");
        writer.WriteLine("}");
        writer.WriteLine("static void ct_thread_publish_ready(void) { if (ct_atomic_load_relaxed(&ct_runtime_phase) != CT_RUNTIME_INITIALIZING) ct_fail(\"CTT0002\", \"<runtime-init>\", 0); ct_atomic_store_release(&ct_runtime_phase, CT_RUNTIME_READY); }");
        writer.WriteLine("void ct_thread_attach(void)");
        writer.WriteLine("{");
        writer.WriteLine("    if (ct_thread_current() != NULL || ct_atomic_load_acquire(&ct_runtime_phase) != CT_RUNTIME_READY) ct_fail(\"CTT0002\", \"<thread-attach>\", 0);");
        writer.WriteLine("    ct_thread_state* state = (ct_thread_state*)calloc(1u, sizeof(ct_thread_state));");
        writer.WriteLine("    if (state == NULL) ct_fail(\"CTM0001\", \"<thread-attach>\", 0);");
        writer.WriteLine("    state->HeapAllocated = true;");
        writer.WriteLine("    (void)ct_atomic_fetch_add_relaxed(&ct_attached_thread_count, 1u);");
        writer.WriteLine("    if (ct_atomic_load_acquire(&ct_runtime_phase) != CT_RUNTIME_READY) { (void)ct_atomic_fetch_sub_release(&ct_attached_thread_count, 1u); free(state); ct_fail(\"CTT0002\", \"<thread-attach>\", 0); }");
        writer.WriteLine("    ct_thread_set_current(state);");
        writer.WriteLine("}");
        writer.WriteLine("void ct_thread_detach(void)");
        writer.WriteLine("{");
        writer.WriteLine("    ct_thread_state* state = ct_thread_current();");
        writer.WriteLine("    if (state == NULL || state->CleanupTop != NULL || state->ReleaseHead != NULL || state->ReleaseDraining) ct_fail(\"CTT0002\", \"<thread-detach>\", 0);");
        if (_usesExceptions)
            writer.WriteLine("    if (state->ExceptionTop != NULL || state->CurrentException != NULL) ct_fail(\"CTT0002\", \"<thread-detach>\", 0);");
        writer.WriteLine("    bool heap_allocated = state->HeapAllocated;");
        writer.WriteLine("    ct_thread_set_current(NULL);");
        writer.WriteLine("    if (ct_atomic_fetch_sub_release(&ct_attached_thread_count, 1u) == 0u) ct_fail(\"CTT0002\", \"<thread-detach>\", 0);");
        writer.WriteLine("    if (heap_allocated) free(state);");
        writer.WriteLine("}");
        writer.WriteLine("static void ct_thread_begin_shutdown(void)");
        writer.WriteLine("{");
        writer.WriteLine("    uint32_t expected = CT_RUNTIME_READY;");
        writer.WriteLine("    if (!ct_atomic_compare_exchange_release(&ct_runtime_phase, &expected, CT_RUNTIME_SHUTTING_DOWN) || ct_atomic_load_acquire(&ct_attached_thread_count) != 1u) ct_fail(\"CTT0002\", \"<runtime-shutdown>\", 0);");
        writer.WriteLine("}");
        writer.WriteLine("void ct_runtime_initialize(const ct_runtime_config* config)");
        writer.WriteLine("{");
        writer.WriteLine("    if (ct_atomic_load_acquire(&ct_runtime_phase) != CT_RUNTIME_UNINITIALIZED) ct_fail(\"CTT0002\", \"<runtime-init>\", 0);");
        writer.WriteLine("    if (config != NULL) { if (config->Size != sizeof(ct_runtime_config)) ct_fail(\"CTT0003\", \"<runtime-init>\", 0); ct_installed_panic_handler = config->PanicHandler; ct_installed_panic_context = config->PanicContext; }");
        writer.WriteLine("    ct_thread_attach_primary(&ct_primary_thread_state);");
        writer.WriteLine("    if (ct_program_module.AbiVersion != CTILDE_RUNTIME_ABI_VERSION) ct_fail(\"CTT0003\", \"<runtime-init>\", 0);");
        writer.WriteLine("    ct_runtime_faults_init();");
        if (_usesExceptions)
        {
            writer.WriteLine("    jmp_buf ct_init_jump;");
            writer.WriteLine("    ct_exception_frame ct_init_frame = { &ct_init_jump, ct_primary_thread_state.ExceptionTop, ct_primary_thread_state.CleanupTop };");
            writer.WriteLine("    ct_primary_thread_state.ExceptionTop = &ct_init_frame;");
            writer.WriteLine("    if (setjmp(ct_init_jump) != 0)");
            writer.WriteLine("    {");
            writer.WriteLine("        ct_object* exception = ct_primary_thread_state.CurrentException;");
            writer.WriteLine("        ct_primary_thread_state.CurrentException = NULL;");
            writer.WriteLine("        ct_primary_thread_state.ExceptionTop = ct_init_frame.Previous;");
            writer.WriteLine("        ct_program_module.Finalize();");
            writer.WriteLine("        ct_unhandled_exception(exception);");
            writer.WriteLine("    }");
            writer.WriteLine("    ct_program_module.Initialize();");
            writer.WriteLine("    ct_primary_thread_state.ExceptionTop = ct_init_frame.Previous;");
        }
        else
            writer.WriteLine("    ct_program_module.Initialize();");
        writer.WriteLine("    ct_thread_publish_ready();");
        writer.WriteLine("}");
        writer.WriteLine("void ct_runtime_shutdown(void)");
        writer.WriteLine("{");
        writer.WriteLine("    if (ct_thread_current() != &ct_primary_thread_state) ct_fail(\"CTT0002\", \"<runtime-shutdown>\", 0);");
        writer.WriteLine("    ct_thread_begin_shutdown();");
        writer.WriteLine("    ct_program_module.Finalize();");
        if (EmitDebugObjects)
            writer.WriteLine("    ct_debug_report_leaks();");
        writer.WriteLine("    ct_thread_detach();");
        writer.WriteLine("}");
        writer.WriteLine("#if defined(CT_MEMORY_DIAGNOSTICS)");
        writer.WriteLine("uint32_t ct_memory_diagnostic_attached_threads(void) { return ct_atomic_load_relaxed(&ct_attached_thread_count); }");
        writer.WriteLine("#endif");
    }

    private void EmitInstrumentedDebugRuntime(CWriter writer)
    {
        writer.WriteLine("static void ct_debug_refresh_runtime_summary(void)");
        writer.WriteLine("{");
        if (EmitDebugObjects)
        {
            writer.WriteLine("    ct_debug_runtime_summary.LiveObjectCount = ct_atomic_load_relaxed(&ct_debug_live_count);");
            writer.WriteLine("    ct_debug_runtime_summary.TotalAllocations = ct_atomic_load_relaxed(&ct_debug_allocation_count);");
            writer.WriteLine("    ct_debug_runtime_summary.TotalFinalReleases = ct_atomic_load_relaxed(&ct_debug_final_release_count);");
            writer.WriteLine("    ct_debug_registry_acquire();");
            writer.WriteLine("    ct_debug_runtime_summary.QuarantineBlocks = ct_debug_quarantine_count;");
            writer.WriteLine("    ct_debug_runtime_summary.QuarantineBytes = (uintptr_t)ct_debug_quarantine_bytes;");
            writer.WriteLine("    ct_debug_registry_release();");
        }
        else
            writer.WriteLine("    ct_debug_runtime_summary.LiveObjectCount = 0u; ct_debug_runtime_summary.TotalAllocations = 0u; ct_debug_runtime_summary.TotalFinalReleases = 0u; ct_debug_runtime_summary.QuarantineBlocks = 0u; ct_debug_runtime_summary.QuarantineBytes = 0u;");
        writer.WriteLine("    ct_debug_runtime_summary.CurrentSite = ct_debug_control.CurrentSite;");
        writer.WriteLine("}");
        writer.WriteLine("static CT_DEBUG_NOINLINE void ct_debug_trap(void)");
        writer.WriteLine("{");
        if (IsEspIdf)
            writer.WriteLine("    esp_cpu_dbgr_break();");
        else
        {
            writer.WriteLine("#if defined(_MSC_VER)");
            writer.WriteLine("    __debugbreak();");
            writer.WriteLine("#else");
            writer.WriteLine("    (void)raise(SIGTRAP);");
            writer.WriteLine("#endif");
        }
        writer.WriteLine("}");
        writer.WriteLine("CT_DEBUG_NOINLINE void ct_debug_keep(void* storage) { ct_debug_probe_sink ^= (uintptr_t)storage; }");
        writer.WriteLine("static void ct_debug_stop_acquire(void) { uint32_t expected; do { expected = 0u; } while (!ct_atomic_compare_exchange_relaxed(&ct_debug_stop_lock, &expected, 1u)); ct_atomic_acquire_fence(); }");
        writer.WriteLine("static void ct_debug_stop_release(void) { ct_atomic_store_release(&ct_debug_stop_lock, 0u); }");
        if (IsEspIdf)
        {
            writer.WriteLine("extern void esp_gdbstub_putchar(int value);");
            writer.WriteLine("extern void esp_gdbstub_flush(void);");
            writer.WriteLine("extern void esp_rom_uart_putc(char value);");
            writer.WriteLine("static char ct_debug_hex_digit(uint8_t value) { return (char)(value < 10u ? (uint8_t)'0' + value : (uint8_t)'a' + value - 10u); }");
            writer.WriteLine("static void ct_debug_console_packet(const uint8_t* data, size_t length) { uint8_t checksum = (uint8_t)'O'; esp_gdbstub_putchar('$'); esp_gdbstub_putchar('O'); for (size_t index = 0u; index < length; ++index) { char high = ct_debug_hex_digit((uint8_t)(data[index] >> 4u)); char low = ct_debug_hex_digit((uint8_t)(data[index] & UINT8_C(0x0f))); checksum = (uint8_t)(checksum + (uint8_t)high + (uint8_t)low); esp_gdbstub_putchar((int)high); esp_gdbstub_putchar((int)low); } esp_gdbstub_putchar('#'); esp_gdbstub_putchar((int)ct_debug_hex_digit((uint8_t)(checksum >> 4u))); esp_gdbstub_putchar((int)ct_debug_hex_digit((uint8_t)(checksum & UINT8_C(0x0f)))); }");
            writer.WriteLine("static void ct_debug_console_write(const char* data, size_t length) { if (data == NULL || length == 0u) return; if (ct_debug_control.SessionActive == 0u) { for (size_t index = 0u; index < length; ++index) esp_rom_uart_putc(data[index]); return; } ct_debug_stop_acquire(); size_t offset = 0u; while (offset < length) { size_t chunk = length - offset > 16u ? 16u : length - offset; ct_debug_console_packet((const uint8_t*)data + offset, chunk); offset += chunk; } ct_debug_stop_release(); }");
            writer.WriteLine("static void ct_debug_console_flush(void) { if (ct_debug_control.SessionActive == 0u) return; ct_debug_stop_acquire(); esp_gdbstub_flush(); ct_debug_stop_release(); }");
        }
        writer.WriteLine("void ct_debug_method_enter(ct_debug_method_frame* frame) { ct_thread_state* state = ct_thread_require_attached(); frame->State = state; frame->Previous = state->DebugFrameTop; frame->Activation = ++state->DebugNextActivation; frame->Active = true; state->DebugFrameTop = frame; ++state->DebugDepth; }");
        writer.WriteLine("void ct_debug_method_leave(void* value) { ct_debug_method_frame* frame = (ct_debug_method_frame*)value; if (!frame->Active) return; ct_thread_state* state = (ct_thread_state*)frame->State; frame->Active = false; if (state == NULL || state->DebugDepth == 0u || state->DebugFrameTop != frame) ct_fail(\"CTM0003\", \"<debug-depth>\", 0); state->DebugFrameTop = frame->Previous; --state->DebugDepth; }");
        writer.WriteLine("CT_DEBUG_NOINLINE void ct_debug_site(uint32_t site)");
        writer.WriteLine("{");
        writer.WriteLine("    ct_thread_state* state = ct_thread_require_attached();");
        writer.WriteLine("    state->DebugCurrentSite = site;");
        writer.WriteLine("    if (ct_debug_control.SessionActive == 0u || site >= ct_debug_control.SiteCount) return;");
        writer.WriteLine("    bool stop = (ct_debug_control.Enabled[site / 32u] & (UINT32_C(1) << (site % 32u))) != 0u;");
        writer.WriteLine("    if (!stop && ct_debug_control.SelectedThread == (uintptr_t)(void*)state) {");
        writer.WriteLine("        if (ct_debug_control.StepMode == 1u) stop = true;");
        writer.WriteLine("        else if (ct_debug_control.StepMode == 2u && state->DebugDepth <= ct_debug_control.StepDepth) stop = true;");
        writer.WriteLine("        else if (ct_debug_control.StepMode == 3u && state->DebugDepth < ct_debug_control.StepDepth) stop = true;");
        writer.WriteLine("    }");
        writer.WriteLine("    if (!stop) return;");
        writer.WriteLine("    ct_debug_stop_acquire(); ct_debug_control.StepMode = 0u; ct_debug_control.CurrentThread = (uintptr_t)(void*)state; ct_debug_control.CurrentActivation = state->DebugFrameTop == NULL ? 0u : state->DebugFrameTop->Activation; ct_debug_control.CurrentSite = site; ct_debug_control.CurrentReason = CT_DEBUG_REASON_SITE; ct_debug_control.CurrentObject = 0u; ct_debug_control.CurrentValue = state->DebugDepth; ct_debug_control.CurrentCode = 0u; ct_debug_control.CurrentFile = 0u; ct_debug_control.CurrentLine = 0;");
        writer.WriteLine("    ct_debug_refresh_runtime_summary(); ct_debug_trap(); ct_debug_stop_release();");
        writer.WriteLine("}");
        writer.WriteLine("static void ct_debug_runtime_event(uint32_t reason, uint32_t mask, ct_object* object, uint32_t value, const char* code, const char* file, int32_t line)");
        writer.WriteLine("{");
        writer.WriteLine("    if (ct_debug_control.SessionActive == 0u || (ct_debug_control.EventMask & mask) == 0u) return;");
        writer.WriteLine("    ct_thread_state* state = ct_thread_current(); ct_debug_stop_acquire(); ct_debug_control.CurrentThread = (uintptr_t)(void*)state; ct_debug_control.CurrentActivation = state == NULL || state->DebugFrameTop == NULL ? 0u : state->DebugFrameTop->Activation; ct_debug_control.CurrentSite = state == NULL ? UINT32_MAX : state->DebugCurrentSite; ct_debug_control.CurrentReason = reason; ct_debug_control.CurrentObject = (uintptr_t)(void*)object; ct_debug_control.CurrentValue = value; ct_debug_control.CurrentCode = (uintptr_t)(const void*)code; ct_debug_control.CurrentFile = (uintptr_t)(const void*)file; ct_debug_control.CurrentLine = line; ct_debug_refresh_runtime_summary(); ct_debug_trap(); ct_debug_stop_release();");
        writer.WriteLine("}");
        writer.WriteLine("CT_DEBUG_NOINLINE void ct_debug_throw_hook(ct_object* exception, const char* code, const char* file, int line, uint32_t unhandled) { ct_debug_probe_sink = (uintptr_t)(void*)exception ^ (uintptr_t)(unsigned int)line ^ (uintptr_t)unhandled; ct_debug_runtime_event(CT_DEBUG_REASON_THROW, unhandled != 0u ? CT_DEBUG_EVENT_UNHANDLED : CT_DEBUG_EVENT_THROW, exception, unhandled, code, file, line); }");
        writer.WriteLine("CT_DEBUG_NOINLINE void ct_debug_fatal_hook(const char* code, const char* file, int line) { ct_debug_probe_sink = (uintptr_t)(unsigned int)line; ct_debug_runtime_event(CT_DEBUG_REASON_FATAL, CT_DEBUG_EVENT_FATAL, NULL, 0u, code, file, line); }");
        if (EmitDebugObjects)
        {
            writer.WriteLine("static void ct_debug_object_initialized(ct_object* object) { ct_debug_allocation* allocation = ct_debug_allocation_for(object); ct_thread_state* state = ct_thread_current(); ct_atomic_store_relaxed(&allocation->LastSite, state == NULL ? UINT32_MAX : state->DebugCurrentSite); ct_debug_runtime_event(CT_DEBUG_REASON_ALLOC, CT_DEBUG_EVENT_ALLOC, object, ct_atomic_load_relaxed(&object->RefCount), NULL, NULL, 0); }");
            writer.WriteLine("static void ct_debug_arc_touch(ct_object* object) { if (object == NULL || ct_atomic_load_relaxed(&object->RefCount) == UINT32_MAX) return; ct_debug_allocation* allocation = ct_debug_allocation_for(object); ct_thread_state* state = ct_thread_current(); ct_atomic_store_relaxed(&allocation->LastSite, state == NULL ? UINT32_MAX : state->DebugCurrentSite); }");
            writer.WriteLine("static void ct_debug_report_leaks(void) { uint32_t count = ct_atomic_load_relaxed(&ct_debug_live_count); if (count == 0u) return; (void)fprintf(stderr, \"C~ debug: %\" PRIu32 \" managed object(s) remain live at shutdown\\n\", count); ct_debug_runtime_event(CT_DEBUG_REASON_LEAK, CT_DEBUG_EVENT_LEAK, ct_debug_live_head == NULL ? NULL : (ct_object*)(void*)(ct_debug_live_head + 1), count, NULL, NULL, 0); }");
        }
        if (IsEspIdf)
        {
            writer.WriteLine("void ct_debug_startup_probe(void) { if (ct_debug_control.SessionActive == 0u || (ct_debug_control.EventMask & CT_DEBUG_EVENT_STARTUP) == 0u) return; ct_debug_stop_acquire(); ct_debug_control.CurrentThread = 0u; ct_debug_control.CurrentActivation = 0u; ct_debug_control.CurrentSite = UINT32_MAX; ct_debug_control.CurrentReason = CT_DEBUG_REASON_STARTUP; ct_debug_refresh_runtime_summary(); ct_debug_trap(); ct_debug_stop_release(); }");
            writer.WriteLine("void ct_debug_wait_for_client(void)");
            writer.WriteLine("{");
            writer.WriteLine("    int64_t start = ct_esp_timer_get_time_us();");
            writer.WriteLine("    while (ct_debug_control.StartupReleased == 0u && ct_esp_timer_get_time_us() - start < INT64_C(15000000)) ct_esp_delay_ms(UINT32_C(10));");
            writer.WriteLine("}");
        }
    }

    private void EmitBoxLayouts(CWriter writer)
    {
        foreach (var type in BoxedTypes)
            writer.WriteLine($"typedef struct {BoxName(type)} {{ ct_object Object; {CDeclaration(type, "Value")}; }} {BoxName(type)};");
        if (_boxedTypes.Count > 0)
            writer.WriteLine();
    }

    private void EmitGlobals(CWriter writer)
    {
        foreach (var field in EmittedTypes.SelectMany(type => type.Fields).Where(field => field.IsStatic && field.Name != "<underlying>"))
        {
            writer.WriteLine($"static {CDeclaration(field.Type, field.CName)} = {DefaultValue(field.Type)};");
        }
        if (EmittedTypes.SelectMany(type => type.Fields).Any(field => field.IsStatic && field.Name != "<underlying>"))
            writer.WriteLine();
    }

    private void EmitPrototypes(CWriter writer)
    {
        var emittedExternalSymbols = new HashSet<string>(StringComparer.Ordinal);
        foreach (var type in EmittedTypes.Where(type => type.Kind is not DeclaredTypeKind.Enum and not DeclaredTypeKind.Opaque))
        {
            foreach (var constructor in type.Constructors)
            {
                if (!_reachableMethods.Contains(constructor))
                    continue;
                writer.WriteLine(MethodSignature(constructor, prototype: true));
                if (type.Kind == DeclaredTypeKind.Class)
                {
                    var parameters = new[] { $"{NameMangler.Type(type)}* ct_self" }
                        .Concat(constructor.Parameters.Select(parameter => CParameterDeclaration(parameter, NameMangler.Identifier(parameter.Name))));
                    writer.WriteLine($"static void {ConstructorInitializerName(constructor)}({string.Join(", ", parameters)});");
                }
            }
            foreach (var method in type.Methods)
            {
                if (IsEspIdf && method.ExternName == "ct_environment_exit")
                    continue;
                if (method.ExternName is not null && !emittedExternalSymbols.Add(method.ExternName))
                    continue;
                if (method.ExternName is null && !_reachableMethods.Contains(method))
                    continue;
                writer.WriteLine(MethodSignature(method, prototype: true));
            }
            foreach (var property in type.Properties)
            {
                if (!_reachableProperties.Contains(property))
                    continue;
                var self = property.IsStatic ? string.Empty : $"{InstanceStorageType(type)}* ct_self";
                if (property.Getter is not null)
                    writer.WriteLine("static " + CFunctionDeclaration(property.Type, NameMangler.Getter(property), self.Length == 0 ? [] : [self]) + ";");
                if (property.Setter is not null)
                {
                    var parameters = self.Length == 0
                        ? new[] { CDeclaration(property.Type, NameMangler.Identifier("value")) }
                        : new[] { self, CDeclaration(property.Type, NameMangler.Identifier("value")) };
                    writer.WriteLine("static " + CFunctionDeclaration(CType.Void, NameMangler.Setter(property), parameters) + ";");
                }
            }
        }
    }
}
