namespace CTilde;

internal sealed partial class CEmitter
{
    private void EmitRuntimeIoSupport(CWriter writer)
    {
        if (!_externUses.Any(use => use.Method.ExternName is { } name &&
                (name.StartsWith("ct_host_file_", StringComparison.Ordinal) || name.StartsWith("ct_host_stream_", StringComparison.Ordinal) ||
                 name.StartsWith("ct_host_directory_", StringComparison.Ordinal) || name == "ct_host_path_separator")))
            return;
        var result = Model.Types["System.Runtime.RuntimeResult"];
        var transfer = Model.Types["System.Runtime.RuntimeTransferResult"];
        var runtimeMetadata = Model.Types["System.Runtime.RuntimeFileMetadata"];
        var runtimeTimestamp = Model.Types["System.Runtime.RuntimeFileTimestamp"];
        var metadata = Model.Types["System.IO.FileMetadata"];
        var timestamp = Model.Types["System.IO.FileTimestamp"];
        var handle = CTypeName(Model.Types["System.IO.FileHandle"].Type);
        var fileMode = CTypeName(Model.Types["System.IO.FileMode"].Type);
        var fileAccess = CTypeName(Model.Types["System.IO.FileAccess"].Type);
        var seekOrigin = CTypeName(Model.Types["System.IO.SeekOrigin"].Type);
        var byteArray = NameMangler.Array(CType.Byte);
        var stringArray = NameMangler.Array(CType.String);
        var resultType = CTypeName(result.Type);
        var transferType = CTypeName(transfer.Type);
        var runtimeMetadataType = CTypeName(runtimeMetadata.Type);
        var metadataType = CTypeName(metadata.Type);
        string F(TypeSymbol type, string name) => type.Fields.Single(field => field.Name == name).CAccessPath;
        string RS(string name) => F(result, name);
        string TS(string name) => F(transfer, name);
        string RM(string name) => F(runtimeMetadata, name);
        string RT(string name) => F(runtimeTimestamp, name);
        string M(string name) => F(metadata, name);
        string T(string name) => F(timestamp, name);
        string Impl(RuntimeImplementationRole role) => IsManagedModule
            ? $"ct_managed_io_{role}"
            : Model.RuntimeImplementations.TryGetValue(role, out var method)
                ? method.CName
                : $"ct_runtime_missing_{role}";
        var used = _externUses.Select(use => use.Method.ExternName).Where(name => name is not null).ToHashSet(StringComparer.Ordinal);
        var usesFile = used.Any(name => name!.StartsWith("ct_host_file_", StringComparison.Ordinal) || name.StartsWith("ct_host_stream_", StringComparison.Ordinal));
        var usesFilesystem = used.Any(name => name == "ct_host_path_separator" || name!.StartsWith("ct_host_directory_", StringComparison.Ordinal) ||
            name is "ct_host_file_exists" or "ct_host_file_delete" or "ct_host_file_move" or "ct_host_file_metadata");

        if (IsManagedModule)
            EmitManagedModuleIoAdapters(writer, result, transfer, runtimeMetadata, runtimeTimestamp,
                resultType, transferType, runtimeMetadataType, RS, TS, RM, RT);

        writer.WriteLine("static CT_NORETURN void ct_runtime_io_fail(const char* code, uint8_t status, int32_t native_code) { (void)status; (void)native_code; ct_raise_runtime_fault(CT_FAULT_IO, code, \"<runtime-service>\", 0); }");
        writer.WriteLine($"static void ct_runtime_io_check({resultType} result, const char* code) {{ if ((uint8_t)result.{RS("Status")} != 0u) ct_runtime_io_fail(code, (uint8_t)result.{RS("Status")}, result.{RS("NativeCode")}); }}");
        writer.WriteLine("static ct_native_utf8_string ct_runtime_path(ct_string* path) { (void)ct_require_nonnull(path, \"<runtime-io>\", 0); if (memchr(path->Data, 0, (size_t)path->Length) != NULL) ct_raise_runtime_fault(CT_FAULT_ARGUMENT, \"CTI0001\", \"<runtime-service>\", 0); return (ct_native_utf8_string){ path, path->Data, (size_t)path->Length }; }");

        if (usesFile)
        {
            writer.WriteLine($"{handle} ct_host_file_open(ct_string* path, {fileMode} mode, {fileAccess} access) {{ uintptr_t value = 0u; {resultType} result = {Impl(RuntimeImplementationRole.FileOpen)}(ct_runtime_path(path), ({CTypeName(Model.Types["System.Runtime.RuntimeFileMode"].Type)})mode, ({CTypeName(Model.Types["System.Runtime.RuntimeFileAccess"].Type)})access, &value); ct_runtime_io_check(result, \"CTI0101\"); if (value == 0u) ct_runtime_io_fail(\"CTI0102\", UINT8_C(11), 0); return ({handle})value; }}");
            writer.WriteLine($"uintptr_t ct_host_file_read({handle} handle, uint8_t* data, size_t length) {{ {transferType} result = {Impl(RuntimeImplementationRole.FileRead)}((uintptr_t)handle, data, length); uint8_t status = (uint8_t)result.{TS("Status")}; if (status == UINT8_C(1)) return 0u; if (status != 0u) ct_runtime_io_fail(\"CTI0103\", status, result.{TS("NativeCode")}); if ((size_t)result.{TS("Count")} > length) ct_runtime_io_fail(\"CTI0104\", UINT8_C(11), 0); return (uintptr_t)result.{TS("Count")}; }}");
            writer.WriteLine($"static void ct_runtime_file_write_all(uintptr_t handle, const uint8_t* data, size_t length) {{ size_t offset = 0u; while (offset < length) {{ {transferType} result = {Impl(RuntimeImplementationRole.FileWrite)}(handle, data + offset, length - offset); if ((uint8_t)result.{TS("Status")} != 0u) ct_runtime_io_fail(\"CTI0105\", (uint8_t)result.{TS("Status")}, result.{TS("NativeCode")}); size_t count = (size_t)result.{TS("Count")}; if (count == 0u || count > length - offset) ct_runtime_io_fail(\"CTI0106\", UINT8_C(11), 0); offset += count; }} }}");
            writer.WriteLine($"void ct_host_file_write_buffer({handle} handle, const uint8_t* data, size_t length) {{ ct_runtime_file_write_all((uintptr_t)handle, data, length); }}");
            writer.WriteLine($"void ct_host_file_write_string({handle} handle, ct_string* value) {{ (void)ct_require_nonnull(value, \"<runtime-io>\", 0); ct_runtime_file_write_all((uintptr_t)handle, value->Data, (size_t)value->Length); }}");
            writer.WriteLine($"void ct_host_file_close({handle} handle) {{ ct_runtime_io_check({Impl(RuntimeImplementationRole.FileClose)}((uintptr_t)handle), \"CTI0107\"); }}");
            writer.WriteLine($"int64_t ct_host_file_seek({handle} handle, int64_t offset, {seekOrigin} origin) {{ int64_t position = 0; {resultType} result = {Impl(RuntimeImplementationRole.FileSeek)}((uintptr_t)handle, offset, ({CTypeName(Model.Types["System.Runtime.RuntimeSeekOrigin"].Type)})origin, &position); ct_runtime_io_check(result, \"CTI0108\"); return position; }}");
            writer.WriteLine($"int64_t ct_host_file_position({handle} handle) {{ return ct_host_file_seek(handle, 0, ({seekOrigin})UINT8_C(1)); }}");
            writer.WriteLine($"int64_t ct_host_file_length({handle} handle) {{ int64_t length = 0; {resultType} result = {Impl(RuntimeImplementationRole.FileLength)}((uintptr_t)handle, &length); ct_runtime_io_check(result, \"CTI0109\"); return length; }}");
            writer.WriteLine($"void ct_host_file_set_length({handle} handle, int64_t length) {{ ct_runtime_io_check({Impl(RuntimeImplementationRole.FileSetLength)}((uintptr_t)handle, length), \"CTI0110\"); }}");
            writer.WriteLine($"void ct_host_file_flush({handle} handle) {{ ct_runtime_io_check({Impl(RuntimeImplementationRole.FileFlush)}((uintptr_t)handle), \"CTI0111\"); }}");
            writer.WriteLine($"uintptr_t ct_host_stream_open(ct_string* path, {fileMode} mode, {fileAccess} access) {{ return (uintptr_t)ct_host_file_open(path, mode, access); }}");
            writer.WriteLine($"int32_t ct_host_stream_read(uintptr_t handle, {byteArray}* buffer, int32_t offset, int32_t count) {{ return (int32_t)ct_host_file_read(({handle})handle, buffer->Data + offset, (size_t)count); }}");
            writer.WriteLine($"void ct_host_stream_write(uintptr_t handle, {byteArray}* buffer, int32_t offset, int32_t count) {{ ct_runtime_file_write_all(handle, buffer->Data + offset, (size_t)count); }}");
            writer.WriteLine($"int64_t ct_host_stream_seek(uintptr_t handle, int64_t offset, {seekOrigin} origin) {{ return ct_host_file_seek(({handle})handle, offset, origin); }}");
            writer.WriteLine($"int64_t ct_host_stream_position(uintptr_t handle) {{ return ct_host_file_position(({handle})handle); }}");
            writer.WriteLine($"int64_t ct_host_stream_length(uintptr_t handle) {{ return ct_host_file_length(({handle})handle); }}");
            writer.WriteLine($"void ct_host_stream_set_length(uintptr_t handle, int64_t length) {{ ct_host_file_set_length(({handle})handle, length); }}");
            writer.WriteLine($"void ct_host_stream_flush(uintptr_t handle) {{ ct_host_file_flush(({handle})handle); }}");
            writer.WriteLine($"void ct_host_stream_close(uintptr_t handle) {{ ct_host_file_close(({handle})handle); }}");
        }

        if (usesFilesystem)
        {
            writer.WriteLine($"static {metadataType} ct_runtime_metadata_convert({runtimeMetadataType} source) {{ {metadataType} value = {{0}}; value.{M("Kind")} = ({CTypeName(Model.Types["System.IO.FileSystemEntryKind"].Type)})source.{RM("Kind")}; value.{M("Attributes")} = ({CTypeName(Model.Types["System.IO.FileAttributes"].Type)})source.{RM("Attributes")}; value.{M("Length")} = source.{RM("Length")}; value.{M("HasCreationTime")} = source.{RM("HasCreationTime")}; value.{M("CreationTime")}.{T("Seconds")} = source.{RM("CreationTime")}.{RT("Seconds")}; value.{M("CreationTime")}.{T("Nanoseconds")} = source.{RM("CreationTime")}.{RT("Nanoseconds")}; value.{M("HasAccessTime")} = source.{RM("HasAccessTime")}; value.{M("AccessTime")}.{T("Seconds")} = source.{RM("AccessTime")}.{RT("Seconds")}; value.{M("AccessTime")}.{T("Nanoseconds")} = source.{RM("AccessTime")}.{RT("Nanoseconds")}; value.{M("HasModificationTime")} = source.{RM("HasModificationTime")}; value.{M("ModificationTime")}.{T("Seconds")} = source.{RM("ModificationTime")}.{RT("Seconds")}; value.{M("ModificationTime")}.{T("Nanoseconds")} = source.{RM("ModificationTime")}.{RT("Nanoseconds")}; return value; }}");
            writer.WriteLine($"static bool ct_runtime_path_metadata(ct_string* path, {runtimeMetadataType}* metadata) {{ {resultType} result = {Impl(RuntimeImplementationRole.PathMetadata)}(ct_runtime_path(path), metadata); uint8_t status = (uint8_t)result.{RS("Status")}; if (status == UINT8_C(3)) return false; if (status != 0u) ct_runtime_io_fail(\"CTI0201\", status, result.{RS("NativeCode")}); return true; }}");
            writer.WriteLine($"bool ct_host_file_exists(ct_string* path) {{ {runtimeMetadataType} value = {{0}}; return ct_runtime_path_metadata(path, &value) && (uint8_t)value.{RM("Kind")} == UINT8_C(1); }}");
            writer.WriteLine($"bool ct_host_directory_exists(ct_string* path) {{ {runtimeMetadataType} value = {{0}}; return ct_runtime_path_metadata(path, &value) && (uint8_t)value.{RM("Kind")} == UINT8_C(2); }}");
            writer.WriteLine($"{metadataType} ct_host_file_metadata(ct_string* path) {{ {runtimeMetadataType} value = {{0}}; if (!ct_runtime_path_metadata(path, &value)) ct_runtime_io_fail(\"CTI0202\", UINT8_C(3), 0); return ct_runtime_metadata_convert(value); }}");
            writer.WriteLine($"void ct_host_file_delete(ct_string* path) {{ {resultType} result = {Impl(RuntimeImplementationRole.FileDelete)}(ct_runtime_path(path)); if ((uint8_t)result.{RS("Status")} != UINT8_C(3)) ct_runtime_io_check(result, \"CTI0203\"); }}");
            writer.WriteLine($"void ct_host_file_move(ct_string* source, ct_string* destination, bool overwrite) {{ ct_runtime_io_check({Impl(RuntimeImplementationRole.PathMove)}(ct_runtime_path(source), ct_runtime_path(destination), overwrite), \"CTI0204\"); }}");
            writer.WriteLine($"void ct_host_directory_move(ct_string* source, ct_string* destination) {{ ct_runtime_io_check({Impl(RuntimeImplementationRole.PathMove)}(ct_runtime_path(source), ct_runtime_path(destination), false), \"CTI0205\"); }}");
            writer.WriteLine($"void ct_host_directory_create(ct_string* path) {{ ct_runtime_io_check({Impl(RuntimeImplementationRole.DirectoryCreate)}(ct_runtime_path(path)), \"CTI0206\"); }}");
            writer.WriteLine($"void ct_host_directory_delete(ct_string* path, bool recursive) {{ ct_runtime_io_check({Impl(RuntimeImplementationRole.DirectoryDelete)}(ct_runtime_path(path), recursive), \"CTI0207\"); }}");
            writer.WriteLine($"void ct_host_directory_set_current(ct_string* path) {{ ct_runtime_io_check({Impl(RuntimeImplementationRole.CurrentDirectorySet)}(ct_runtime_path(path)), \"CTI0208\"); }}");
            writer.WriteLine($"uint8_t ct_host_path_separator(void) {{ return (uint8_t){Impl(RuntimeImplementationRole.PathSeparator)}(); }}");

            writer.WriteLine($"ct_string* ct_host_directory_get_current(void) {{ size_t capacity = 256u; for (;;) {{ uint8_t* data = (uint8_t*)ct_alloc(capacity, \"<runtime-io>\", 0); {transferType} result = {Impl(RuntimeImplementationRole.CurrentDirectoryGet)}(data, capacity); uint8_t status = (uint8_t)result.{TS("Status")}; size_t count = (size_t)result.{TS("Count")}; if (status == UINT8_C(2)) {{ ct_dealloc(data); capacity = count > capacity ? count : capacity * 2u; continue; }} if (status != 0u || count > capacity || count > (size_t)INT32_MAX) ct_runtime_io_fail(\"CTI0209\", status == 0u ? UINT8_C(11) : status, result.{TS("NativeCode")}); ct_string* value = ct_string_from_bytes(data, (int32_t)count, \"<runtime-io>\", 0); ct_dealloc(data); return value; }} }}");

            writer.WriteLine($"static int ct_runtime_string_compare(ct_string* a, ct_string* b) {{ int32_t count = a->Length < b->Length ? a->Length : b->Length; int value = count == 0 ? 0 : memcmp(a->Data, b->Data, (size_t)count); return value != 0 ? value : a->Length < b->Length ? -1 : a->Length > b->Length ? 1 : 0; }}");
            writer.WriteLine($"{stringArray}* ct_host_directory_entries(ct_string* path) {{ uintptr_t directory = 0u; ct_runtime_io_check({Impl(RuntimeImplementationRole.DirectoryOpen)}(ct_runtime_path(path), &directory), \"CTI0210\"); size_t count = 0u, capacity = 8u; ct_string** values = (ct_string**)ct_alloc(capacity * sizeof(ct_string*), \"<runtime-io>\", 0); for (;;) {{ size_t name_capacity = 256u; uint8_t* name = NULL; {transferType} read; {runtimeMetadataType} item = {{0}}; for (;;) {{ name = (uint8_t*)ct_alloc(name_capacity, \"<runtime-io>\", 0); read = {Impl(RuntimeImplementationRole.DirectoryRead)}(directory, name, name_capacity, &item); uint8_t status = (uint8_t)read.{TS("Status")}; if (status == UINT8_C(2)) {{ size_t required = (size_t)read.{TS("Count")}; ct_dealloc(name); name_capacity = required > name_capacity ? required : name_capacity * 2u; continue; }} break; }} uint8_t status = (uint8_t)read.{TS("Status")}; if (status == UINT8_C(1)) {{ ct_dealloc(name); break; }} size_t name_length = (size_t)read.{TS("Count")}; if (status != 0u || name_length > name_capacity || name_length > (size_t)INT32_MAX) ct_runtime_io_fail(\"CTI0211\", status == 0u ? UINT8_C(11) : status, read.{TS("NativeCode")}); size_t base = (size_t)path->Length; bool separator = base != 0u && path->Data[base - 1u] != (uint8_t)ct_host_path_separator(); size_t full_length = base + (separator ? 1u : 0u) + name_length; uint8_t* full = (uint8_t*)ct_alloc(full_length == 0u ? 1u : full_length, \"<runtime-io>\", 0); (void)memcpy(full, path->Data, base); if (separator) full[base++] = ct_host_path_separator(); (void)memcpy(full + base, name, name_length); ct_dealloc(name); ct_string* value = ct_string_from_bytes(full, (int32_t)full_length, \"<runtime-io>\", 0); ct_dealloc(full); if (count == capacity) {{ size_t next = capacity * 2u; ct_string** replacement = (ct_string**)ct_alloc(next * sizeof(ct_string*), \"<runtime-io>\", 0); (void)memcpy(replacement, values, count * sizeof(ct_string*)); ct_dealloc(values); values = replacement; capacity = next; }} values[count++] = value; }} ct_runtime_io_check({Impl(RuntimeImplementationRole.DirectoryClose)}(directory), \"CTI0212\"); for (size_t index = 1u; index < count; ++index) {{ ct_string* value = values[index]; size_t prior = index; while (prior > 0u && ct_runtime_string_compare(values[prior - 1u], value) > 0) {{ values[prior] = values[prior - 1u]; --prior; }} values[prior] = value; }} if (count > (size_t)INT32_MAX) ct_runtime_io_fail(\"CTI0213\", UINT8_C(11), 0); {stringArray}* result = ct_new_{stringArray}((int32_t)count, \"<runtime-io>\", 0); for (size_t index = 0u; index < count; ++index) result->Data[index] = values[index]; ct_dealloc(values); return result; }}");
        }
        writer.WriteLine();
    }

    private void EmitManagedModuleIoAdapters(CWriter writer, TypeSymbol result,
        TypeSymbol transfer, TypeSymbol metadata, TypeSymbol timestamp, string resultType,
        string transferType, string metadataType, Func<string, string> RS,
        Func<string, string> TS, Func<string, string> RM, Func<string, string> RT)
    {
        writer.WriteLine("static uint8_t ct_managed_io_status(int32_t code) { if (code == 0) return UINT8_C(0); if (code == -ENOBUFS) return UINT8_C(2); if (code == -ENOENT || code == -ENOTDIR) return UINT8_C(3); if (code == -EEXIST) return UINT8_C(4); if (code == -EACCES || code == -EPERM || code == -EROFS) return UINT8_C(5); if (code == -EINVAL || code == -EBADF) return UINT8_C(6); if (code == -ENOTSUP || code == -ENOSYS) return UINT8_C(7); if (code == -EBUSY) return UINT8_C(8); if (code == -ETIMEDOUT) return UINT8_C(9); if (code == -ENOMEM) return UINT8_C(10); return UINT8_C(11); }");
        writer.WriteLine($"static {resultType} ct_managed_io_result(int32_t code) {{ {resultType} value = {{0}}; value.{RS("Status")} = ({CTypeName(result.Fields.Single(field => field.Name == "Status").Type)})ct_managed_io_status(code); value.{RS("NativeCode")} = code < 0 ? -code : code; return value; }}");
        writer.WriteLine($"static {transferType} ct_managed_io_transfer_result(int32_t code, size_t count, bool eof) {{ {transferType} value = {{0}}; value.{TS("Status")} = ({CTypeName(transfer.Fields.Single(field => field.Name == "Status").Type)})(eof && count == 0u && code == 0 ? UINT8_C(1) : ct_managed_io_status(code)); value.{TS("NativeCode")} = code < 0 ? -code : code; value.{TS("Count")} = (uintptr_t)count; return value; }}");
        writer.WriteLine($"static {resultType} ct_managed_io_FileOpen(ct_native_utf8_string path, uint8_t mode, uint8_t access, uintptr_t* handle) {{ ct_runtime_io_open_v19 value = {{ sizeof(value), path.Data, path.ByteLength, mode, access, 0u }}; int32_t code = ct_runtime_api->Service(UINT32_C(32), &value, sizeof(value)); *handle = value.Handle; return ct_managed_io_result(code); }}");
        writer.WriteLine($"static {transferType} ct_managed_io_FileRead(uintptr_t handle, uint8_t* data, size_t length) {{ ct_runtime_io_transfer_v19 value = {{ sizeof(value), handle, data, length, 0u, false }}; int32_t code = ct_runtime_api->Service(UINT32_C(33), &value, sizeof(value)); return ct_managed_io_transfer_result(code, value.Count, value.Eof); }}");
        writer.WriteLine($"static {transferType} ct_managed_io_FileWrite(uintptr_t handle, const uint8_t* data, size_t length) {{ ct_runtime_io_transfer_v19 value = {{ sizeof(value), handle, (uint8_t*)(uintptr_t)(const void*)data, length, 0u, false }}; int32_t code = ct_runtime_api->Service(UINT32_C(34), &value, sizeof(value)); return ct_managed_io_transfer_result(code, value.Count, false); }}");
        writer.WriteLine($"static {resultType} ct_managed_io_FileSeek(uintptr_t handle, int64_t offset, uint8_t origin, int64_t* result) {{ ct_runtime_io_seek_v19 value = {{ sizeof(value), handle, offset, origin, 0 }}; int32_t code = ct_runtime_api->Service(UINT32_C(35), &value, sizeof(value)); *result = value.Value; return ct_managed_io_result(code); }}");
        writer.WriteLine($"static {resultType} ct_managed_io_FileLength(uintptr_t handle, int64_t* result) {{ ct_runtime_io_value_v19 value = {{ sizeof(value), handle, 0 }}; int32_t code = ct_runtime_api->Service(UINT32_C(36), &value, sizeof(value)); *result = value.Value; return ct_managed_io_result(code); }}");
        writer.WriteLine($"static {resultType} ct_managed_io_FileSetLength(uintptr_t handle, int64_t length) {{ ct_runtime_io_value_v19 value = {{ sizeof(value), handle, length }}; return ct_managed_io_result(ct_runtime_api->Service(UINT32_C(37), &value, sizeof(value))); }}");
        writer.WriteLine($"static {resultType} ct_managed_io_FileFlush(uintptr_t handle) {{ ct_runtime_io_handle_v19 value = {{ sizeof(value), handle }}; return ct_managed_io_result(ct_runtime_api->Service(UINT32_C(38), &value, sizeof(value))); }}");
        writer.WriteLine($"static {resultType} ct_managed_io_FileClose(uintptr_t handle) {{ ct_runtime_io_handle_v19 value = {{ sizeof(value), handle }}; return ct_managed_io_result(ct_runtime_api->Service(UINT32_C(39), &value, sizeof(value))); }}");
        writer.WriteLine($"static {resultType} ct_managed_io_PathMetadata(ct_native_utf8_string path, {metadataType}* output) {{ ct_runtime_io_metadata_v19 value = {{0}}; value.Size = sizeof(value); value.Path = path.Data; value.PathLength = path.ByteLength; int32_t code = ct_runtime_api->Service(UINT32_C(48), &value, sizeof(value)); if (code == 0) {{ output->{RM("Kind")} = ({CTypeName(metadata.Fields.Single(field => field.Name == "Kind").Type)})value.Kind; output->{RM("Attributes")} = ({CTypeName(metadata.Fields.Single(field => field.Name == "Attributes").Type)})value.Attributes; output->{RM("Length")} = value.Length; output->{RM("HasCreationTime")} = value.HasCreationTime; output->{RM("CreationTime")}.{RT("Seconds")} = value.CreationSeconds; output->{RM("CreationTime")}.{RT("Nanoseconds")} = value.CreationNanoseconds; output->{RM("HasAccessTime")} = value.HasAccessTime; output->{RM("AccessTime")}.{RT("Seconds")} = value.AccessSeconds; output->{RM("AccessTime")}.{RT("Nanoseconds")} = value.AccessNanoseconds; output->{RM("HasModificationTime")} = value.HasModificationTime; output->{RM("ModificationTime")}.{RT("Seconds")} = value.ModificationSeconds; output->{RM("ModificationTime")}.{RT("Nanoseconds")} = value.ModificationNanoseconds; }} return ct_managed_io_result(code); }}");
        writer.WriteLine($"static {resultType} ct_managed_io_FileDelete(ct_native_utf8_string path) {{ ct_runtime_io_path_flag_v19 value = {{ sizeof(value), path.Data, path.ByteLength, false }}; return ct_managed_io_result(ct_runtime_api->Service(UINT32_C(49), &value, sizeof(value))); }}");
        writer.WriteLine($"static {resultType} ct_managed_io_PathMove(ct_native_utf8_string source, ct_native_utf8_string destination, bool overwrite) {{ ct_runtime_io_two_paths_v19 value = {{ sizeof(value), source.Data, source.ByteLength, destination.Data, destination.ByteLength, overwrite }}; return ct_managed_io_result(ct_runtime_api->Service(UINT32_C(50), &value, sizeof(value))); }}");
        writer.WriteLine($"static {resultType} ct_managed_io_DirectoryCreate(ct_native_utf8_string path) {{ ct_runtime_io_path_flag_v19 value = {{ sizeof(value), path.Data, path.ByteLength, false }}; return ct_managed_io_result(ct_runtime_api->Service(UINT32_C(51), &value, sizeof(value))); }}");
        writer.WriteLine($"static {resultType} ct_managed_io_DirectoryDelete(ct_native_utf8_string path, bool recursive) {{ ct_runtime_io_path_flag_v19 value = {{ sizeof(value), path.Data, path.ByteLength, recursive }}; return ct_managed_io_result(ct_runtime_api->Service(UINT32_C(52), &value, sizeof(value))); }}");
        writer.WriteLine($"static {resultType} ct_managed_io_DirectoryOpen(ct_native_utf8_string path, uintptr_t* handle) {{ ct_runtime_io_open_v19 value = {{0}}; value.Size = sizeof(value); value.Path = path.Data; value.PathLength = path.ByteLength; int32_t code = ct_runtime_api->Service(UINT32_C(53), &value, sizeof(value)); *handle = value.Handle; return ct_managed_io_result(code); }}");
        writer.WriteLine($"static {transferType} ct_managed_io_DirectoryRead(uintptr_t handle, uint8_t* name, size_t capacity, {metadataType}* output) {{ ct_runtime_io_directory_read_v19 value = {{ sizeof(value), handle, name, capacity, 0u, 0u, 0u, 0 }}; int32_t code = ct_runtime_api->Service(UINT32_C(54), &value, sizeof(value)); if (code == 1) return ct_managed_io_transfer_result(0, 0u, true); if (code == 0) {{ output->{RM("Kind")} = ({CTypeName(metadata.Fields.Single(field => field.Name == "Kind").Type)})value.Kind; output->{RM("Attributes")} = ({CTypeName(metadata.Fields.Single(field => field.Name == "Attributes").Type)})value.Attributes; output->{RM("Length")} = value.Length; }} return ct_managed_io_transfer_result(code, value.NameLength, false); }}");
        writer.WriteLine($"static {resultType} ct_managed_io_DirectoryClose(uintptr_t handle) {{ ct_runtime_io_handle_v19 value = {{ sizeof(value), handle }}; return ct_managed_io_result(ct_runtime_api->Service(UINT32_C(55), &value, sizeof(value))); }}");
        writer.WriteLine($"static {transferType} ct_managed_io_CurrentDirectoryGet(uint8_t* data, size_t length) {{ ct_runtime_io_transfer_v19 value = {{ sizeof(value), 0u, data, length, 0u, false }}; int32_t code = ct_runtime_api->Service(UINT32_C(56), &value, sizeof(value)); return ct_managed_io_transfer_result(code, value.Count, false); }}");
        writer.WriteLine($"static {resultType} ct_managed_io_CurrentDirectorySet(ct_native_utf8_string path) {{ ct_runtime_io_path_flag_v19 value = {{ sizeof(value), path.Data, path.ByteLength, false }}; return ct_managed_io_result(ct_runtime_api->Service(UINT32_C(57), &value, sizeof(value))); }}");
        writer.WriteLine("static uint8_t ct_managed_io_PathSeparator(void) { int32_t value = ct_runtime_api->Service(UINT32_C(58), NULL, 0u); return value > 0 && value <= UINT8_MAX ? (uint8_t)value : (uint8_t)'/'; }");
    }
}
